field.widget.settings.current_workflow_state_widget:
  type: mapping
  label: 'Field widget format settings for the current workflow state field.'
  mapping:
    title:
      type: string
      label: 'The title to use for the field widget.'
    title_display:
      type: string
      label: 'The setting that determines how the field widget title is displayed.'
    show_for_new_entities:
      type: boolean
      label: 'The setting that allows to show the widget on entity creation forms.'

field.widget.settings.state_machine_buttons:
  type: mapping
  label: 'Settings for the state machine buttons field widget.'
  mapping:
    use_transition_label:
      type: integer
