taxonomy.vocabulary.*.third_party.rdf_entity:
  type: mapping
  label: 'RDF Entity third party settings'
  mapping:
    graph:
      type: sequence
      sequence:
        type: string
        label: 'The mapping of a graph definition to a graph uri.'
    mapping:
      type: sequence
      sequence:
        type: sequence
        sequence:
          type: string
          label: 'Mapping of field properies to their rdf counterpart.'

taxonomy.vocabulary.*.third_party.rdf_taxonomy:
  type: mapping
  label: 'RDF Taxonomy third party settings'
  mapping:
    locked:
      type: boolean
      label: 'If true, terms cannot be added or edited via UI'
