facet.widget.config.links_inline:
  type: facet.widget.default_config
  label: 'Inline links widget configuration'
  mapping:
    all_text:
      type: label
      translatable: true
      label: 'All text'
    prefix_text:
      type: label
      translatable: true
      label: 'Prefix text'
    suffix_text:
      type: label
      translatable: true
      label: 'Suffix text'
    cache_contexts:
      type: sequence
      label: 'Cache contexts'
      sequence:
        type: string
        labe: 'Cache context'
