<?php

/**
 * @file
 * Main functions and hook implementations of the Licence module.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function joinup_licence_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {
  // Make sure the licence label is unique.
  if ($entity_type->id() == 'rdf_entity' && $bundle == 'licence' && !empty($fields['label'])) {
    $fields['label']->addConstraint('UniqueFieldInBundle', ['bundles' => ['licence']]);
  }
}

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function joinup_licence_rdf_entity_access(EntityInterface $entity, $operation, AccountInterface $account) {
  if ($entity->bundle() !== 'spdx_licence' || $operation !== 'view') {
    return AccessResult::neutral();
  }

  // Only deny access to the canonical route.
  $route_match = \Drupal::routeMatch();
  return AccessResult::forbiddenIf($route_match->getRouteName() === 'entity.rdf_entity.canonical' && $route_match->getParameter('rdf_entity')->bundle() === 'spdx_licence');
}
