solution.settings:
  type: config_object
  label: 'Solution workflow permission settings'
  mapping:
    transitions:
      type: sequence
      label: 'Allowed transitions'
      sequence:
        type: sequence
        label: 'Target state'
        sequence:
          type: sequence
          label: 'Source state'
          sequence:
            type: string
            label: 'Role'

action.configuration.joinup_transfer_solution_ownership:
  type: action_configuration_default
  label: 'Transfer the ownership of the solution to the selected member'
