<?php

/**
 * @file
 * Includes installation functions for the rdf_entity module.
 */

/**
 * Implements hook_requirements().
 */
function rdf_entity_requirements($phase) {
  $requirements = [];
  if ($phase !== 'runtime') {
    return $requirements;
  }

  $requirements += rdf_entity_virtuoso_version_requirements();
  $requirements += rdf_entity_virtuoso_permission_requirements();
  return $requirements;
}
