<?php

/**
 * @file
 * Main functions and hook implementations of the RDF Entity module.
 */

use Drupal\Core\Config\Entity\ConfigEntityBundleBase;
use Drupal\Core\Config\Entity\ConfigEntityInterface;
use Drupal\Core\Database\Database;
use Drupal\Core\Entity\BundleEntityFormBase;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Url;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\rdf_entity\Entity\RdfEntitySparqlStorage;
use Drupal\rdf_entity\RdfFieldHandler;
use Drupal\rdf_entity\RdfInterface;
use EasyRdf\Http;

/**
 * Implements hook_entity_base_field_info_alter().
 */
function rdf_entity_entity_base_field_info_alter(&$fields, EntityTypeInterface $entity_type) {
  if (!(\Drupal::entityManager()->getStorage($entity_type->id()) instanceof RdfEntitySparqlStorage)) {
    return;
  }

  $fields['graph'] = BaseFieldDefinition::create('uri')
    ->setLabel(t('The graph where the entity is stored.'))
    ->setTargetEntityTypeId('rdf_entity')
    ->setName('graph')
    ->setComputed(TRUE);
}

/**
 * Implements hook_entity_type_alter().
 */
function rdf_entity_entity_type_alter(array &$entity_types) {
  if (isset($entity_types['field_storage_config'])) {
    // Swap out the field storage settings form.
    $entity_types['field_storage_config']->setFormClass('edit', '\Drupal\rdf_entity\Form\RdfFieldStorageConfigEditForm');
  }
}

/**
 * Implements hook_form_alter().
 */
function rdf_entity_form_field_storage_config_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Only add mapping form element to fields of entities implementing
  // RdfEntitySparqlStorage.
  $id = $form_state->get('entity_type_id');
  if (!$id) {
    return;
  }
  $storage = \Drupal::entityManager()->getStorage($id);
  if (!$storage instanceof RdfEntitySparqlStorage) {
    return;
  }

  $form_obj = $form_state->getFormObject();
  /** @var \Drupal\field\Entity\FieldStorageConfig $entity */
  $entity = $form_obj->getEntity();
  $schema = $entity->getSchema();
  $form['rdf_mapping'] = [
    '#type' => 'details',
    '#title' => t('Rdf field mapping'),
    '#description' => t('This field uses a Sparql backend. Please map the fields to their corresponding rdf properties.'),
    '#weight' => 99,
  ];
  foreach ($schema['columns'] as $column => $column_desc) {
    $description = isset($column_desc['description']) ? $column_desc['description'] . "<br>" : '';
    foreach (['type', 'length', 'size', 'serialize'] as $key) {
      if (!empty($column_desc[$key])) {
        $description .= '<strong>' . $key . "</strong>: " . $column_desc[$key] . ' ';
      }
    }

    $settings = rdf_entity_get_third_party_property($entity, 'mapping', $column);

    $form['rdf_mapping'][$column] = [
      '#type' => 'details',
      '#title' => $column,
      '#description' => $description,
    ];

    $form['rdf_mapping'][$column]['predicate_' . $column] = [
      '#type' => 'url',
      '#title' => t('Mapping'),
      '#weight' => 150,
      '#default_value' => isset($settings['predicate']) ? $settings['predicate'] : '',
    ];

    $form['rdf_mapping'][$column]['format_' . $column] = [
      '#type' => 'select',
      '#title' => t('Value format'),
      '#options' => RdfFieldHandler::getSupportedDatatypes(),
      '#empty_value' => 'no_format',
      '#weight' => 151,
      '#default_value' => isset($settings['format']) ? $settings['format'] : NULL,
    ];
  }

  $form['#entity_builders'][] = 'rdf_entity_form_alter_builder';
}

/**
 * Retrieve nested third party settings from object.
 */
function rdf_entity_get_third_party_property(ConfigEntityInterface $object, $property, $column, $default = NULL) {
  $property_value = $object->getThirdPartySetting('rdf_entity', $property, FALSE);
  if (!is_array($property_value) || !isset($property_value[$column])) {
    return $default;
  }
  return $property_value[$column];
}

/**
 * Entity builder callback: Save rdf field mapping.
 */
function rdf_entity_form_alter_builder($entity_type, FieldStorageConfig $entity, array &$form, FormStateInterface $form_state) {
  $schema = $entity->getSchema();
  $data = [];
  foreach ($schema['columns'] as $column => $column_desc) {
    $data[$column]['predicate'] = $form_state->getValue('predicate_' . $column);
    $data[$column]['format'] = $form_state->getValue('format_' . $column);

  }
  $entity->setThirdPartySetting('rdf_entity', 'mapping', $data);
}

/**
 * Implements hook_entity_create().
 */
function rdf_entity_entity_create(EntityInterface $entity) {
  $entity_type = $entity->getEntityTypeId();
  $storage = \Drupal::entityManager()->getStorage($entity_type);
  if ($storage instanceof RdfEntitySparqlStorage) {
    // The target graph should be the graph of the entity when it's created.
    $entity->set('graph', $storage->getGraphHandler()->getTargetGraphFromEntity($entity));
  }
}

/**
 * Implements hook_form_alter().
 *
 * Configurations for the RDF entity bundle.
 */
function rdf_entity_form_alter(&$form, FormStateInterface $form_state) {
  $form_obj = $form_state->getFormObject();
  if (!$form_obj instanceof BundleEntityFormBase) {
    return;
  }
  /** @var \Drupal\Core\Config\Entity\ConfigEntityBundleBase $entity */
  $entity = $form_obj->getEntity();
  if (!$entity instanceof ConfigEntityBundleBase) {
    return;
  }
  $entity_name = $entity->getEntityType()->getBundleOf();
  /** @var \Drupal\rdf_entity\Entity\RdfEntitySparqlStorage $storage */
  $storage = \Drupal::entityManager()->getStorage($entity_name);
  if (!$storage instanceof RdfEntitySparqlStorage) {
    return;
  }
  $base_fields = \Drupal::entityManager()->getBaseFieldDefinitions($entity_name);
  $idKey = $storage->getEntityType()->getKey('id');

  $form['rdf_entity'] = [
    '#type' => 'details',
    '#title' => t('RDF Entity'),
    '#description' => t('RDF entity configurations.'),
    '#open' => TRUE,
    '#weight' => 99,
  ];

  /** @var \Drupal\rdf_entity\RdfEntityIdPluginManager $id_plugin_manager */
  $id_plugin_manager = \Drupal::service('plugin.manager.rdf_entity.id');
  $plugins = array_map(function (array $definition) use ($id_plugin_manager) {
    return $definition['name'];
  }, $id_plugin_manager->getDefinitions());

  $form['rdf_entity']['entity_id_plugin'] = [
    '#type' => 'select',
    '#title' => t('Entity ID generator'),
    '#description' => t("The generator used to create IDs for new entities."),
    '#options' => $plugins,
    '#default_value' => $entity->getThirdPartySetting('rdf_entity', 'entity_id_plugin') ?: $id_plugin_manager->getFallbackPluginId(NULL),
  ];

  $form['rdf_entity']['rdf_graph'] = [
    '#type' => 'details',
    '#title' => t('Graphs'),
    '#description' => t('Graph URI mapping'),
  ];
  foreach ($storage->getGraphDefinitions() as $definedGraphName => $definedGraph) {
    $default_value = rdf_entity_get_third_party_property($entity, 'graph', $definedGraphName, FALSE);
    $form['rdf_entity']['rdf_graph']['graph_' . $definedGraphName] = [
      '#type' => 'url',
      '#title' => $definedGraph['title'],
      '#description' => $definedGraph['description'],
      '#default_value' => $default_value,
      '#required' => TRUE,
    ];
  }

  $form['rdf_entity']['rdf_mapping'] = [
    '#type' => 'details',
    '#title' => t('Field mapping'),
    '#description' => t('This entity type uses a Sparql backend. Please map the bundle base fields to their corresponding RDF properties.'),
  ];

  /** @var \Drupal\Core\Field\BaseFieldDefinition $base_field */
  foreach ($base_fields as $id => $base_field) {
    $columns = $base_field->getColumns();
    // The entity id doesn't need a mapping,
    // as this is the subject of the triple.
    if ($id == $idKey) {
      continue;
    }
    foreach ($columns as $column_name => $column) {
      $settings = rdf_entity_get_third_party_property($entity, 'mapping', $id, FALSE);
      $title = $base_field->getLabel();
      if (count($columns) > 1) {
        $title .= ' (' . $column_name . ')';
      }

      $form['rdf_entity']['rdf_mapping'][$id] = [
        '#type' => 'details',
        '#title' => $title,
        '#description' => $base_field->getDescription(),
      ];

      $form['rdf_entity']['rdf_mapping'][$id]['predicate_' . $id . '_' . $column_name] = [
        '#type' => 'url',
        '#title' => t('Mapping'),
        '#description' => t('The rdf predicate.'),
        '#weight' => 150,
        '#default_value' => isset($settings[$column_name]['predicate']) ? $settings[$column_name]['predicate'] : NULL,
      ];

      $form['rdf_entity']['rdf_mapping'][$id]['format_' . $id . '_' . $column_name] = [
        '#type' => 'select',
        '#title' => t('Value format'),
        '#description' => t('The rdf format. Required if format is filled.'),
        '#options' => RdfFieldHandler::getSupportedDatatypes(),
        '#empty_value' => '',
        '#weight' => 151,
        '#default_value' => isset($settings[$column_name]['format']) ? $settings[$column_name]['format'] : NULL,
      ];
    }
  }
  $form['#entity_builders'][] = 'rdf_entity_bundle_config';
}

/**
 * Store the mapping of fields and rdf properties.
 */
function rdf_entity_bundle_config($entity_type, ConfigEntityInterface $entity, array &$form, FormStateInterface $form_state) {
  $entity_name = $entity->getEntityType()->getBundleOf();
  $base_fields = \Drupal::entityManager()->getBaseFieldDefinitions($entity_name);
  $storage = \Drupal::entityManager()->getStorage($entity_name);
  $idKey = $storage->getEntityType()->getKey('id');
  $entity->setThirdPartySetting('rdf_entity', 'entity_id_plugin', $form_state->getValue('entity_id_plugin'));
  $third_party_settings = [];
  /** @var \Drupal\Core\Field\BaseFieldDefinition $base_field */
  foreach ($base_fields as $id => $base_field) {
    if ($id == $idKey) {
      continue;
    }
    $columns = $base_field->getColumns();
    foreach ($columns as $column_name => $column) {
      $third_party_settings[$id][$column_name]['predicate'] = $form_state->getValue('predicate_' . $id . '_' . $column_name);
      $third_party_settings[$id][$column_name]['format'] = $form_state->getValue('format_' . $id . '_' . $column_name);
    }
  }
  $entity->setThirdPartySetting('rdf_entity', 'mapping', $third_party_settings);
  $third_party_settings = [];
  foreach ($storage->getGraphDefinitions() as $definedGraphName => $definedGraph) {
    $graph_uri = $form_state->getValue('graph_' . $definedGraphName);
    $third_party_settings[$definedGraphName] = $graph_uri;
  }
  $entity->setThirdPartySetting('rdf_entity', 'graph', $third_party_settings);
}

/**
 * Implements hook_theme().
 */
function rdf_entity_theme() {
  return [
    'rdf_entity' => [
      'render element' => 'elements',
    ],
    'rdf_add_list' => [
      'variables' => ['content' => NULL],
    ],
  ];
}

/**
 * Prepares variables for rdf entity templates.
 *
 * Default template: rdf-entity.html.twig.
 *
 * Themes should use their own copy of rdf-entity.html.twig.
 * The default is located inside "templates/rdf-entity.html.twig".
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An array of elements to display in view mode.
 *   - rdf_entity: The rdf_entity object.
 *   - view_mode: View mode; e.g., 'full', 'teaser', etc.
 */
function template_preprocess_rdf_entity(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  // Provide a distinct $teaser boolean.
  $variables['teaser'] = $variables['view_mode'] == 'teaser';
  $variables['rdf_entity'] = $variables['elements']['#rdf_entity'];
  /** @var \Drupal\rdf_entity\RdfInterface $rdf_entity */
  $rdf_entity = $variables['rdf_entity'];
  $variables['date'] = drupal_render($variables['elements']['created']);
  unset($variables['elements']['created']);
  $variables['author_name'] = drupal_render($variables['elements']['uid']);
  unset($variables['elements']['uid']);

  $variables['url'] = $rdf_entity->url('canonical', [
    'language' => $rdf_entity->language(),
  ]);
  $variables['label'] = !empty($variables['elements']['label']) ? $variables['elements']['label'] : ['#markup' => $rdf_entity->label()];
  unset($variables['elements']['label']);
  // The view mode is 'full' and we are on the 'rdf_entity.view' route.
  $variables['page'] = ($variables['view_mode'] == 'full' && (rdf_entity_is_page($rdf_entity)));

  // Helpful $content variable for templates.
  $variables += ['content' => []];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }

  // Add article ARIA role.
  $variables['attributes']['role'] = 'article';
}

/**
 * Prepares variables for list of available rdf type templates.
 *
 * Default template: rdf-add-list.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - content: An array of rdf bundles.
 */
function template_preprocess_rdf_add_list(array &$variables) {
  $variables['types'] = [];
  if (!empty($variables['content'])) {
    foreach ($variables['content'] as $type) {
      $variables['types'][$type->id()] = [
        'type' => $type->id(),
        'add_link' => \Drupal::l($type->label(), new Url('rdf_entity.rdf_add', ['rdf_type' => $type->id()])),
        'description' => [
          '#markup' => $type->getDescription(),
        ],
      ];
    }
  }
}

/**
 * Is the current page the full page view of the passed-in RDF entity?
 *
 * @param \Drupal\rdf_entity\RdfInterface $rdf_entity
 *   An RDF entity.
 *
 * @return int|false
 *   The ID of the RDF entity if this is a full page view, otherwise FALSE.
 */
function rdf_entity_is_page(RdfInterface $rdf_entity) {
  $route_match = \Drupal::routeMatch();
  if ($route_match->getRouteName() == 'entity.rdf_entity.canonical') {
    $page_rdf_entity = $route_match->getParameter('rdf_entity');
  }
  return (!empty($page_rdf_entity) ? $page_rdf_entity->id() == $rdf_entity->id() : FALSE);
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function rdf_entity_theme_suggestions_rdf_entity(array $variables) {
  $suggestions = [];
  $rdf_entity = $variables['elements']['#rdf_entity'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'rdf_entity__' . $sanitized_view_mode;
  $suggestions[] = 'rdf_entity__' . $rdf_entity->bundle();
  $suggestions[] = 'rdf_entity__' . $rdf_entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'rdf_entity__' . $rdf_entity->id();
  $suggestions[] = 'rdf_entity__' . $rdf_entity->id() . '__' . $sanitized_view_mode;

  return $suggestions;
}

/**
 * Returns the requirements related to virtuoso version.
 *
 * @return array
 *   The virtuoso version requirements.
 */
function rdf_entity_virtuoso_version_requirements() {
  $minimum_version = '07.00.0000';
  $requirements = [
    'rdf_entity_endpoint' => [
      'title' => t('Virtuoso endpoint availability'),
      'description' => t('Virtuoso endpoint is available.'),
    ],
    'rdf_entity_virtuoso_version' => [
      'title' => t('Virtuoso version'),
      'description' => t('Virtuoso version meets minimum requirements.'),
    ],
  ];

  /** @var \Drupal\rdf_entity\Database\Driver\sparql\Connection $connection */
  $connection = Database::getConnection('default', 'sparql_default');
  $client = Http::getDefaultHttpClient();
  $client->resetParameters(TRUE);
  $client->setUri($connection->getQueryUri());
  $client->setMethod('GET');

  try {
    $response = $client->request();
  }
  catch (Exception $e) {
    // If the endpoint could not be reached, return early.
    $requirements['rdf_entity_endpoint']['description'] = t('Virtuoso endpoint could not be reached.');
    $requirements['rdf_entity_endpoint']['severity'] = REQUIREMENT_ERROR;
    return $requirements;
  }

  $server_header = $response->getHeader('Server');
  preg_match('/Virtuoso\/(.*?)\s/', $server_header, $matches);
  $version = (is_array($matches) && count($matches) === 2) ? $matches[1] : [];
  if (version_compare($version, $minimum_version, 'lt')) {
    $description = t('The minimum virtuoso version supported is :version', [
      ':version' => $minimum_version,
    ]);
    $requirements['rdf_entity_virtuoso_version']['description'] = $description;
    $requirements['rdf_entity_virtuoso_version']['severity'] = REQUIREMENT_ERROR;
    $requirements['rdf_entity_virtuoso_version']['value'] = $version;
  }

  return $requirements;
}

/**
 * Returns the requirements related to virtuoso query permissions.
 *
 * Since there is no direct way to draw information from the virtuoso instace
 * the function simply tries to create a triple in a random graph and then
 * delete the whole graph.
 *
 * @return array
 *   The virtuoso query requirements.
 */
function rdf_entity_virtuoso_permission_requirements() {
  $rand = random_int(10000, 50000);
  $uri = 'http://example.com/id/rdf_entity_' . $rand;
  $query = <<<QUERY
    WITH <{$uri}>
    INSERT { <{$uri}> <http://example.com/predicate> "test value" }
    CLEAR GRAPH <{$uri}>
QUERY;

  /** @var \Drupal\rdf_entity\Database\Driver\sparql\Connection $connection */
  $connection = Database::getConnection('default', 'sparql_default');
  $requirements = [
    'rdf_entity_virtuoso_query' => [
      'title' => t('Virtuoso permissions'),
      'description' => t('Virtuoso update/delete permissions are properly set.'),
      'value' => $query,
    ],
  ];

  try {
    $connection->query($query);
  }
  catch (Exception $e) {
    $requirements['rdf_entity_virtuoso_query']['description'] = $e->getMessage();
    $requirements['rdf_entity_virtuoso_query']['severity'] = REQUIREMENT_ERROR;
  }

  return $requirements;
}
