<?php

/**
 * @file
 * Contains joinup_document.module.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\og\Og;

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function joinup_document_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {
  // @todo Add test coverage for these constraints.
  // @see https://webgate.ec.europa.eu/CITnet/jira/browse/ISAICP-2499
  if ($entity_type->id() == 'node' && $bundle == 'document') {
    if (!empty($fields['field_document_short_title'])) {
      $fields['field_document_short_title']->addConstraint('UniqueField');
    }
    if (!empty($fields['title'])) {
      $fields['title']->addConstraint('UniqueFieldInBundle', ['bundles' => ['document']]);
    }
  }
}

/**
 * Implements hook_node_access().
 */
function joinup_document_node_access(EntityInterface $entity, $operation, AccountInterface $account) {
  if ($entity->bundle() !== 'document' || $account->hasPermission('administer nodes')) {
    return AccessResult::neutral();
  }

  switch ($operation) {
    case 'view':
      $parent = \Drupal::service('joinup_document.relations_manager')->getDocumentParent($entity);

      /** @var \Drupal\Core\Entity\EntityAccessControlHandlerInterface $access_handler */
      $access_handler = \Drupal::service('entity_type.manager')->getAccessControlHandler('rdf_entity');
      if (!$access_handler->access($parent, 'view', $account)) {
        return AccessResult::forbidden();
      }

      $membership = Og::getMembership($parent, $account);
      if (empty($membership)) {
        return AccessResult::neutral();
      }

      if (!$entity->isPublished() && $membership->hasPermission('view any unpublished content')) {
        return AccessResult::allowed();
      }
      break;

    case 'update':
      $allowed_transitions = $entity->get('field_document_state')->first()->getTransitions();
      return AccessResult::forbiddenIf(empty($allowed_transitions));
  }

  return AccessResult::neutral();
}

/**
 * Returns the appropriate workflow to use for the document entity.
 *
 * The callback ensures that even if the parent is updated and the moderation
 * status changes, it will still use the proper workflow.
 * The fact that both pre and post moderated workflow use the same states
 * ensures that there are not going to be any issues as we only change
 * transitions.
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *    The document entity.
 *
 * @return string
 *    The id of the workflow to use.
 *
 * @throws Exception
 *    Thrown when the function is called for a different bundle.
 */
function joinup_document_workflow_selector(EntityInterface $entity) {
  if ($entity->bundle() != 'document') {
    throw new Exception("This method can only be called for document entities.");
  }
  /** @var \Drupal\joinup_document\JoinupDocumentRelationManager $relation_manager */
  $relation_manager = \Drupal::service('joinup_document.relations_manager');
  return $relation_manager->getDocumentWorkflow($entity);
}
