<?php

/**
 * @file
 * Hook implementations for the Joinup Document module.
 */

declare(strict_types = 1);

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\joinup_document\Entity\Document;

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function joinup_document_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {
  // @todo Add test coverage for these constraints.
  // @see https://citnet.tech.ec.europa.eu/CITnet/jira/browse/ISAICP-2499
  if ($entity_type->id() == 'node' && $bundle == 'document') {
    if (!empty($fields['field_short_title'])) {
      $fields['field_short_title']->addConstraint('UniqueField');
    }
    if (!empty($fields['title'])) {
      $fields['title']->addConstraint('UniqueFieldInBundle', ['bundles' => ['document']]);
    }
  }
}

/**
 * Implements hook_entity_bundle_info_alter().
 */
function joinup_document_entity_bundle_info_alter(&$bundles) {
  if (!empty($bundles['node']['document'])) {
    $bundles['node']['document']['class'] = Document::class;
  }
}
