<?php

/**
 * @file
 * Main functions and hook implementations of the Joinup SPARQL module.
 */

declare(strict_types = 1);

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function joinup_sparql_form_rdf_entity_confirm_form_alter(array &$form, FormStateInterface $form_state, string $form_id): void {
  /** @var \Drupal\Core\Entity\ContentEntityConfirmFormBase $form_object */
  $form_object = $form_state->getFormObject();
  $form['#title'] = t('Are you sure you want to delete entity %name?', [
    '%name' => $form_object->getEntity()->label(),
  ]);
}
