# This file is used by Toolkit pipelines, allowing to override the upgrade
# procedure, pre-upgrade steps, cron execution command and extra OS packages
# inside the container.
# See https://webgate.ec.europa.eu/fpfis/wikis/display/MULTISITE/Pipeline+configuration+and+override.
# See \EcEuropa\Toolkit\TaskRunner\Commands\CloneCommands::runDeploy().
upgrade_commands:
  default:
    - ./vendor/bin/drush state:set system.maintenance_mode 1 --input-format=integer --yes
    - touch disable-config-readonly
    - ./vendor/bin/drush deploy --yes
    - ./vendor/bin/drush search-api:reset-tracker --yes
    - ./vendor/bin/drush php:eval "if(node_access_needs_rebuild()) { node_access_rebuild(); }"
    - rm disable-config-readonly
    - ./vendor/bin/drush state:set system.maintenance_mode 0 --input-format=integer --yes
    # These are release v1.75.0 one-time-tasks and will be removed after a
    # successful deployment on production, in the scope of the release ticket.
    # The unpublished content Solr core/server has been removed. We reindexo
    # unpublished content into the unified Solr core/server.
    - ./vendor/bin/drush search-api:clear unpublished
    - ./vendor/bin/drush search-api:index unpublished
  append:
    acceptance:
      - touch disable-config-readonly
      - ./vendor/bin/drush pm:enable joinup_acceptance --yes
      - rm disable-config-readonly

php_version: 7.4

solr: True
solr_version: 6
solr_core: custom

virtuoso_image: registry.fpfis.eu/ec-europa/digit-joinup-reference:virtuoso

install_clean: Yes
install_clone: False

solr_refresh_acc: True
virtuoso_refresh_acc: True
