version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: resources/codedeploy/scripts/cleanup.sh
  AfterInstall:
    - location: resources/codedeploy/scripts/install.sh