# Any value can be overridden in docker-compose.override.yml, a file that is not
# under VCS control. See docker-compose.override.yml.dist for more details.

# CLEAN vs. CLONE install
# Docker compose knows to fire up the containers with databases having data
# imported from the production dumps/snapshots. Read the documentation for the
# DOCKER_RESTORE_PRODUCTION environment variable from .env.dist.

# Accessing services from the host machine
# See docker-compose.override.yml.dist on each service, for more details on how
# to access services from the host machine and how to avoid port collision with
# potential host machine instances. The ports were not exposed by default, in
# the main `docker-compose.yml` file, because they cannot be easily overridden.
# See https://stackoverflow.com/questions/48851190/docker-compose-override-a-ports-property-instead-of-merging-it

version: '3.8'
services:
  web:
    image: fpfis/httpd-php-dev:7.1
    working_dir: /var/www/html
    # macOS users should override 'volumes:' in docker-compose.override.yml.
    # See docker-compose.override.yml.dist.
    volumes:
      - ${PWD}:/var/www/html
    env_file:
      - .env.dist
    environment:
      DOCUMENT_ROOT: "/var/www/html/web"
      SMTP_SERVER: mail
      SMTP_PORT: 1025
      SMTP_FROM: contact@example.com
      DRUPAL_PRIVATE_FILE_SYSTEM: /var/www/html/private
      DRUPAL_FILE_TEMP_PATH: /var/www/html/tmp
      # Environment variables without a value will receive the values from the
      # host machine, if they are set. Sensitive information such as
      # user credentials should be placed in .env file.
      # See https://docs.docker.com/compose/environment-variables/#pass-environment-variables-to-containers
      DRUPAL_HASH_SALT:
      ASDA_URL:
      ASDA_USER:
      ASDA_PASSWORD:
      DISABLE_XDEBUG:
      DISABLE_BLACKFIRE:
      # For non-macOS hosts. For macOS, see docker-compose.override.yml.dist.
      XDEBUG_CONFIG: "client_host=172.17.0.1"
      XDEBUG_MODE: "develop, debug"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - mysql
      - sparql
      - solr
      - redis
      - mail
      - selenium

  mysql:
    image: mysql:5.7
    # macOS users should override 'volumes:' in docker-compose.override.yml.
    # See docker-compose.override.yml.dist.
    volumes:
      - ./resources/docker/mysql/config:/etc/mysql/conf.d
      # MySQL dump.
      - ./db/mysql/dump:/db/mysql/dump
      # Contains a script to run when waking up.
      - ./scripts/docker/mysql:/docker-entrypoint-initdb.d
    env_file:
      - .env.dist
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'joinup'
      DOCKER_RESTORE_PRODUCTION:

  sparql:
    image: tenforce/virtuoso
    # macOS users should override 'volumes:' in docker-compose.override.yml.
    # See docker-compose.override.yml.dist.
    volumes:
      - ./db/virtuoso/snapshot:/data/backups
      - ./scripts/docker/virtuoso/entrypoint.sh:/entrypoint.sh
    environment:
      SPARQL_UPDATE: 'true'
      # Virtuoso .ini overrides. Pattern: VIRT_$SECTION_$KEY=$VALUE
      # See https://hub.docker.com/r/tenforce/virtuoso
      VIRT_Parameters_O_DIRECT: 1
      VIRT_Parameters_ThreadCleanupInterval: 1
      VIRT_Parameters_NumberOfBuffers: 340000
      VIRT_Parameters_MaxDirtyBuffers: 250000
      VIRT_Replication_ServerEnable: 0
      VIRT_SPARQL_ResultSetMaxRows: 1000000
      DOCKER_RESTORE_PRODUCTION:
    command:
      - '/bin/bash'
      - '-c'
      - 'chmod +x /entrypoint.sh && /entrypoint.sh'

  solr:
    image: solr:6
    # macOS users should override 'volumes:' in docker-compose.override.yml.
    # See docker-compose.override.yml.dist.
    volumes:
      - ./db/solr:/solr/snapshot
      - ./web/modules/contrib/search_api_solr/solr-conf/6.x:/solr/conf
      - ./scripts/solr/restore_solr.sh:/opt/solr/bin/restore_solr.sh
      - ./scripts/docker/solr/precreate.sh:/docker-entrypoint-initdb.d/precreate.sh
    environment:
      DOCKER_RESTORE_PRODUCTION:

  redis:
    image: redis

  mail:
    image: mailhog/mailhog

  # Includes a Selenium server accessible at port 5900.
  # See docker-compose.override.yml.dist
  selenium:
    image: selenium/standalone-chrome-debug
    environment:
      - DISPLAY=:99
      - SE_OPTS=-debug
      - VNC_NO_PASSWORD=1
