# Any value can be overridden in docker-compose.override.yml, a file that is not
# under VCS control. See docker-compose.override.yml.dist for more details.

version: '3'
services:
  web:
    image: fpfis/httpd-php-dev:7.1
    working_dir: /var/www/html
    ports:
      - '8080:8080'
    # macOS users should override 'volumes:' in docker-compose.override.yml.
    # See docker-compose.override.yml.dist.
    volumes:
      - ${PWD}:/var/www/html
    env_file:
      - .env.dist
    environment:
      DOCUMENT_ROOT: "/var/www/html/web"
#      PHP_XDEBUG_ENABLED: "0"
#      PHP_IDE_CONFIG: "serverName=Docker"
#      PHP_SENDMAIL_PATH: "/usr/sbin/sendmail -t -i -S mail:1025"
      SMTP_SERVER: mail
      SMTP_PORT: 1025
      SMTP_FROM: contact@example.com
      # Environment variables without a value will receive the values from the
      # host machine, if they are set.
      # See https://docs.docker.com/compose/environment-variables/#pass-environment-variables-to-containers
      DRUPAL_HASH_SALT:
      ASDA_URL:
      ASDA_USER:
      ASDA_PASSWORD:
    depends_on:
      - mysql
      - virtuoso
      - solr
      - redis
      - mail
      - selenium

  mysql:
    image: mysql:5.7
    # macOS users should override 'volumes:' in docker-compose.override.yml.
    # See docker-compose.override.yml.dist.
    ports:
      # Avoid port collision with a potential host machine instance of MySQL.
      - '3307:3306'
    volumes:
      - ./resources/docker/mysql/config:/etc/mysql/conf.d
      # MySQL dump.
      - ./db/mysql/dump/mysql.sql:/db/mysql/dump/mysql.sql
      # Contains a script to run when waking up.
      - ./scripts/docker/mysql:/docker-entrypoint-initdb.d
    env_file:
      - .env.dist
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'joinup'
      DOCKER_RESTORE_PRODUCTION:

  virtuoso:
    image: tenforce/virtuoso
    ports:
      # Avoid port collision with a potential host machine instance of Virtuoso.
      - '8891:8890'
    volumes:
      - ./db/virtuoso/snapshot:/data/backups
    environment:
      SPARQL_UPDATE: 'true'
      # Virtuoso .ini overrides. Pattern: VIRT_$SECTION_$KEY=$VALUE
      # See https://hub.docker.com/r/tenforce/virtuoso
      VIRT_Parameters_O_DIRECT: 1
      VIRT_Parameters_ThreadCleanupInterval: 1
      VIRT_Parameters_NumberOfBuffers: 340000
      VIRT_Parameters_MaxDirtyBuffers: 250000
      VIRT_Replication_ServerEnable: 0
      VIRT_SPARQL_ResultSetMaxRows: 1000000
      # In order to bring up the Virtuoso without restoring from backup, set an
      # empty value in docker-compose.override.yml.
      BACKUP_PREFIX: JOINUP_FULL_DUMP_

  solr:
    image: solr:6
    ports:
      # Avoid port collision with a potential host machine instance of Solr.
      - '8984:8983'
    # macOS users should override 'volumes:' in docker-compose.override.yml.
    # See docker-compose.override.yml.dist.
    volumes:
      - ./db/solr:/solr/snapshot
      - ./web/modules/contrib/search_api_solr/solr-conf/6.x:/solr/conf
      - ./scripts/solr/restore_solr.sh:/opt/solr/bin/restore_solr.sh
    entrypoint:
      - docker-entrypoint.sh
      - bash
      - '-c'
      - 'mkdir -p /opt/docker-solr/drupal/conf ; cp -r /solr/conf/* /opt/docker-solr/drupal/conf/ ; sed -i "/solr.install.dir=/c\solr.install.dir=/opt/solr" /opt/docker-solr/drupal/conf/solrcore.properties ; precreate-core drupal_published /opt/docker-solr/drupal ; precreate-core drupal_unpublished /opt/docker-solr/drupal ; exec solr -f'
    # Restore the Solr production snapshot:
    # docker-compose exec solr /opt/solr/bin/restore_solr.sh --core drupal_published --snapshot-name published --timeout 120 --snapshot-dir /solr/snapshot --solr-url http://localhost:8983/solr
    # docker-compose exec solr /opt/solr/bin/restore_solr.sh --core drupal_unpublished --snapshot-name unpublished --timeout 120 --snapshot-dir /solr/snapshot --solr-url http://localhost:8983/solr

  redis:
    image: redis
    ports:
      # Avoid port collision with a potential host machine instance of Redis.
      - '6380:6379'

  mail:
    image: mailhog/mailhog
    ports:
      # Avoid port collision with a potential host machine instance of Mailhog.
      - '1026:1025'
      - '8026:8025'

  # Spawn a Selenium server, including also a VNC server on localhost:5900 (the
  # password is "secret")
  selenium:
    image: selenium/standalone-chrome-debug
    environment:
      - DISPLAY=:99
      - SE_OPTS=-debug
    ports:
      - '5900:5900'
    expose:
      - '4444'
