version: '3.4'
services:
  web:
    build:
      context: ./resources/docker/web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./build.docker.main.xml:/var/www/html/build.xml
    env_file:
      - .env.dist
    environment:
      DOCUMENT_ROOT: "/var/www/html/web"
      PHP_XDEBUG_ENABLED: "1"
      PHP_IDE_CONFIG: "serverName=Docker"
      PHP_SENDMAIL_PATH: "/usr/sbin/sendmail -t -i -S mail:1025"

  gulp:
    image: huli/gulp
    volumes:
      - $PWD/web/themes/joinup:/srv
    working_dir: /srv/prototype
    entrypoint:
      - /entrypoint.sh
      - default

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_USER: 'db_user'
      MYSQL_PASSWORD: 'db_pass'
      MYSQL_DATABASE: 'db_name'

  virtuoso:
    image: tenforce/virtuoso
    environment:
      - SPARQL_UPDATE=true
      - DBA_PASSWORD=dba
    volumes:
      - "virtuoso:/data"
    ports:
      - "8890:8890"

  mail:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  selenium:
    image: selenium/standalone-chrome-debug:3.11
    ports:
      - "5900:5900"
    expose:
      - "4440"
    volumes:
      # Needed due to chrome having issues with memory usage. Firefox does not face this issue.
      # @see: https://github.com/elgalu/docker-selenium/issues/20
      - "/dev/shm:/dev/shm"

  solr_published:
    build:
      context: ./resources/docker/solr
    ports:
     - "8982:8983"
    entrypoint:
     - docker-entrypoint.sh
     - solr-precreate
     - drupal_published
     - "/opt/docker-solr/configsets/drupal"

  solr_unpublished:
    build:
      context: ./resources/docker/solr
    ports:
     - "8983:8983"
    entrypoint:
     - docker-entrypoint.sh
     - solr-precreate
     - drupal_unpublished
     - "/opt/docker-solr/configsets/drupal"

volumes:
  virtuoso:
