<?php

/**
 * @file
 * Main functions and hook implementations of the Joinup CCK module.
 */

declare(strict_types = 1);

use Drupal\joinup_cck\Plugin\Field\FieldFormatter\Video;
use Drupal\joinup_cck\Plugin\Filter\VideoEmbedWysiwyg;

define('JOINUP_CCK_EMBED_COOKIE_URL', '//europa.eu/webtools/crs/iframe/?oriurl=');

/**
 * Implements hook_page_attachments().
 */
function joinup_cck_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'joinup_cck/joinup_cck.cck';
}

/**
 * Implements hook_filter_info_alter().
 */
function joinup_cck_filter_info_alter(&$info) {
  if (isset($info['video_embed_wysiwyg'])) {
    $info['video_embed_wysiwyg']['class'] = VideoEmbedWysiwyg::class;
  }
}

/**
 * Implements hook_field_formatter_info_alter().
 */
function joinup_cck_field_formatter_info_alter(array &$info) {
  if (isset($info['video_embed_field_video'])) {
    $info['video_embed_field_video']['class'] = Video::class;
  }
}
