<?php

/**
 * @file
 * Main file of Joinup module.
 */

declare(strict_types = 1);

use Drupal\Core\Form\FormStateInterface;
use Drupal\joinup_collection\JoinupCollectionHelper;
use Drupal\og\Entity\OgMembership;
use Drupal\og\OgMembershipInterface;
use Drupal\rdf_entity\Entity\Rdf;
use Drupal\user\UserInterface;

/**
 * Implements hook_ENTITY_TYPE_insert().
 *
 * Add the 'Joinup' collection membership to every new user.
 */
function joinup_collection_user_insert(UserInterface $account): void {
  /** @var \Drupal\collection\Entity\CollectionInterface $joinup_collection */
  if ($joinup_collection = Rdf::load(JoinupCollectionHelper::getCollectionId())) {
    // Add the membership only it doesn't exist yet.
    if (!$membership = $joinup_collection->getMembership((int) $account->id(), [])) {
      OgMembership::create()
        ->setGroup($joinup_collection)
        ->setOwner($account)
        ->setState(OgMembershipInterface::STATE_ACTIVE)
        ->save();
    }
    // If the membership exists but is not active, activate it.
    elseif ($membership->getState() !== OgMembershipInterface::STATE_ACTIVE) {
      $membership->setState(OgMembershipInterface::STATE_ACTIVE)->save();
    }
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 *
 * Remove the 'joinup_og_membership_delete_action' action.
 */
function joinup_collection_form_views_form_og_members_overview_default_alter(&$form, FormStateInterface $form_state, $form_id): void {
  /** @var \Drupal\views\ViewExecutable $view */
  $view = $form_state->getBuildInfo()['args'][0];
  // The first view argument is the entity type.
  if (isset($view->args[0]) && $view->args[0] === 'rdf_entity') {
    // The second view argument is the group entity ID.
    if (!empty($view->args[1]) && $view->args[1] === JoinupCollectionHelper::getCollectionId()) {
      unset($form['header']['og_membership_bulk_form']['action']['#options']['joinup_og_membership_delete_action']);
    }
  }
}
