<?php
/**
 * @file
 * Procedural lumps of code for the rdf_draft module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\rdf_entity\Entity\RdfEntitySparqlStorage;

/**
 * Implements hook_rdf_graph_definition_alter().
 */
function rdf_draft_rdf_graph_definition_alter(&$definitions) {
  $definitions['default']['title'] = t('Published');
  $definitions['draft'] = [
    'title' => t('Draft'),
    'description' => t('The draft graph used to store entities of this type.'),
  ];
}

/**
 * Implements hook_entity_type_alter().
 */
function rdf_draft_entity_type_alter(array &$entity_types) {
  // Guard condition against infinite recursion.
  static $recurse = FALSE;
  if ($recurse) {
    return;
  }
  foreach ($entity_types as $entity_type_id => $entity_type) {
    if ($entity_type->hasViewBuilderClass() && $entity_type->hasLinkTemplate('canonical')) {
      $recurse = TRUE;
      $storage = \Drupal::service('entity.manager')->getStorage($entity_type_id);
      $recurse = FALSE;
      if ($storage  instanceof RdfEntitySparqlStorage) {
        $entity_type->setLinkTemplate('rdf-draft', "/rdf-draft/$entity_type_id/{{$entity_type_id}}");
      }
    }
  }
}

/**
 * Implements hook_entity_operation().
 */
function rdf_draft_entity_operation(EntityInterface $entity) {
  $operations = array();
  if ($entity->hasLinkTemplate('rdf-draft')) {
    $operations['draft'] = array(
      'title' => t('Draft'),
      'weight' => 100,
      'url' => $entity->toUrl('rdf-draft'),
    );
  }
  return $operations;
}


/**
 * Implements hook_entity_create().
 */
function rdf_draft_entity_create(\Drupal\Core\Entity\EntityInterface $entity) {
  $entity_type = $entity->getEntityTypeId();
  $storage = \Drupal::entityManager()->getStorage($entity_type);
  if ($storage instanceof RdfEntitySparqlStorage) {
    // Create new entities in the draft graph instead of the published.
    $entity->graph = $storage->getGraph($entity->bundle(), 'draft');
  }
}