<?php

/**
 * @file
 * Joinup comment logic.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Link;

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function joinup_comment_comment_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  // Add contextual links to comments.
  $build['#contextual_links']['comment'] = [
    'route_parameters' => ['comment' => $entity->id()],
    'metadata' => ['changed' => $entity->getChangedTime()],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Disallow commenting for anonymous visitors and
 * change the submit button label for the comment form.
 */
function joinup_comment_form_comment_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (Drupal::currentUser()->isAnonymous()) {
    $form['#access'] = FALSE;
    $login_url = Link::createFromRoute('Login', 'user.login')->toString();
    $reg_url = Link::createFromRoute('create an account', 'user.register')->toString();
    $link_text = sprintf('%s or %s to comment.', $login_url, $reg_url);
    $form['#markup'] = '<div class="center">' . $link_text . '</div>';
  }

  $form['actions']['submit']['#value'] = t('Post comment');
}
