<?php

/**
 * @file
 * Provides functionality for the Joinup video module.
 */

declare(strict_types = 1);

use Drupal\Component\Utility\UrlHelper;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

define('JOINUP_VIDEO_EMBED_COOKIE_URL', '//europa.eu/webtools/crs/iframe/?oriurl=');

/**
 * Implements hook_form_video_embed_dialog_alter().
 *
 * - Hides autoplay and responsive settings in the video embed dialog.
 * - Provides a description with examples of valid video URLs.
 */
function joinup_video_form_video_embed_dialog_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['settings']['#access'] = FALSE;
  // @todo: The description should be updated when the rest of the providers are
  // fixed.
  // @see: https://webgate.ec.europa.eu/CITnet/jira/browse/ISAICP-4573
  $form['video_url']['#description'] = 'Youtube and EC videos are allowed.'
    . '<br />Youtube example: https://www.youtube.com/watch?v=dQw4w9WgXcQ'
    . '<br />EC url example: http://europa.eu/123abc!123'
    . '<br />EC video example: https://ec.europa.eu/avservices/video/player.cfm?sitelang=en&ref=ABC12345';
}


/**
 * Implements hook_page_attachments().
 */
function joinup_video_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'joinup_video/joinup_video.cck';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function joinup_video_preprocess_video_embed_iframe(&$variables) {
  // Override the default url and pass it to the ec cck url but ignore iframes
  // that refer to the same site.
  if (!empty($variables['url']) && !UrlHelper::externalIsLocal($variables['url'], \Drupal::request()->getSchemeAndHttpHost())) {
    // video_embed_field prints every part of the URL separately and prints some
    // key characters in the twig directly (e.g. the '#' for the anchor).
    // This makes it difficult to properly encode the full URL to pass it to the
    // cck domain. Pre-create the URL and pass it as an encoded URL.
    $url =  Url::fromUri($variables['url'], [
      'query' => $variables['query'],
      // Fragment is returned as an array, so give NULL to avoid type errors.
      'fragment' => empty($variables['fragment']) ? NULL : $variables['fragment'],
    ]);
    $variables['url'] = JOINUP_VIDEO_EMBED_COOKIE_URL . urlencode($url->setAbsolute()->toString());
    unset($variables['query']);
    unset($variables['fragment']);
  }

}
