<?php

/**
 * @file
 * Provides functionality for the Joinup video module.
 */

declare(strict_types = 1);

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_video_embed_dialog_alter().
 *
 * - Hides autoplay and responsive settings in the video embed dialog.
 * - Provides a description with examples of valid video URLs.
 */
function joinup_video_form_video_embed_dialog_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['settings']['#access'] = FALSE;
  $form['video_url']['#description'] = 'The following providers are allowed:'
    . '<br />Youtube [e.g. https://www.youtube.com/watch?v=dQw4w9WgXcQ]'
    . '<br />EC url [e.g. http://europa.eu/123abc!123]'
    . '<br />EC video [e.g. https://ec.europa.eu/avservices/video/player.cfm?sitelang=en&ref=ABC12345]'
    . '<br />Prezi presentation [e.g. https://prezi.com/embed/somepretziid]'
    . '<br />Google docs [e.g. https://docs.google.com/forms/d/someembeddedid1234/viewform?embedded=true]';
}
