<?php

/**
 * @file
 * Provides functionality for the Joinup video module.
 */

declare(strict_types = 1);

use Drupal\Core\Form\FormStateInterface;
use Drupal\joinup_video\Plugin\Field\FieldFormatter\Video;
use Drupal\joinup_video\Plugin\Filter\VideoEmbedWysiwyg;

define('JOINUP_VIDEO_EMBED_COOKIE_URL', '//europa.eu/webtools/crs/iframe/?oriurl=');

/**
 * Implements hook_form_video_embed_dialog_alter().
 *
 * - Hides autoplay and responsive settings in the video embed dialog.
 * - Provides a description with examples of valid video URLs.
 */
function joinup_video_form_video_embed_dialog_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['settings']['#access'] = FALSE;
  // @todo: The description should be updated when the rest of the providers are
  // fixed.
  // @see: https://webgate.ec.europa.eu/CITnet/jira/browse/ISAICP-4573
  $form['video_url']['#description'] = 'Youtube and EC videos are allowed.'
    . '<br />Youtube example: https://www.youtube.com/watch?v=dQw4w9WgXcQ'
    . '<br />EC url example: http://europa.eu/123abc!123'
    . '<br />EC video example: https://ec.europa.eu/avservices/video/player.cfm?sitelang=en&ref=ABC12345';
}


/**
 * Implements hook_page_attachments().
 */
function joinup_video_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'joinup_video/joinup_video.cck';
}

/**
 * Implements hook_filter_info_alter().
 */
function joinup_video_filter_info_alter(&$info) {
  if (isset($info['video_embed_wysiwyg'])) {
    $info['video_embed_wysiwyg']['class'] = VideoEmbedWysiwyg::class;
  }
}

/**
 * Implements hook_field_formatter_info_alter().
 */
function joinup_video_field_formatter_info_alter(array &$info) {
  if (isset($info['video_embed_field_video'])) {
    $info['video_embed_field_video']['class'] = Video::class;
  }
}
