<?php

/**
 * @file
 * Hook implementations for the Joinup core module.
 */

declare(strict_types = 1);

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Access\AccessResultInterface;
use Drupal\Core\Block\BlockPluginInterface;
use Drupal\Core\Cache\CacheableMetadata;
use Drupal\Core\Cache\RefinableCacheableDependencyInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\StreamWrapper\StreamWrapperManager;
use Drupal\block\BlockInterface;
use Drupal\joinup_core\ETransBlockConfiguration;
use Drupal\joinup_core\Element\Datetime;
use Drupal\joinup_core\Entity\OutdatedContentInterface;
use Drupal\joinup_core\JoinupSiteAlertListBuilder;
use Drupal\joinup_core\Plugin\Field\FieldType\OutdatedContentFieldItemList;
use Drupal\node\NodeInterface;

/**
 * Implements hook_theme().
 */
function joinup_core_theme($existing, $type, $theme, $path) {
  return [
    '404_not_found' => [
      'variables' => [
        'search' => [],
        'front' => [],
      ],
    ],
    'download_link' => [
      'variables' => [
        'attributes' => [],
        'extension' => '',
        'url' => NULL,
        'title' => '',
      ],
    ],
    'vertical_table' => [
      'variables' => [
        'attributes' => [],
        'rows' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_cron().
 */
function joinup_core_cron(): void {
  \Drupal::getContainer()->get('batch.storage')->cleanup();
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 *
 * Alters the Site Alert entity form to hide the scheduling of the alerts. Due
 * to a bug in the core page cache module the scheduling can only work using an
 * additional AJAX call which is undesirable in our case. By disabling the
 * scheduling the alerts are managed manually and the page cache works normally.
 */
function joinup_core_form_site_alert_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['scheduling']['#access'] = FALSE;
}

/**
 * Implements hook_entity_base_field_info().
 *
 * - Provides a 'report' field on community content pages that can be used to
 *   report inappropriate content.
 */
function joinup_core_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];

  // Add a 'report' field to community content entities. Currently all node
  // types are community content.
  if ($entity_type->id() === 'node') {
    $fields['report'] = BaseFieldDefinition::create('report_link')
      ->setName('report')
      ->setLabel(t('Report'))
      ->setComputed(TRUE)
      ->setClass('\Drupal\joinup_core\ReportLinkFieldItemList')
      ->setDisplayConfigurable('view', TRUE)
      ->setDisplayOptions('view', [
        'label' => 'hidden',
        'weight' => 50,
        'settings' => [
          'trim_length' => 80,
          'url_only' => FALSE,
          'url_plain' => FALSE,
          'rel' => '',
          'target' => '',
        ],
      ]);
  }

  return $fields;
}

/**
 * Implements hook_entity_type_alter().
 */
function joinup_core_entity_type_alter(array &$entity_types) {
  // Check that the Site Alert entity type is defined, so we can avoid depending
  // on the Site Alert module.
  if (isset($entity_types['site_alert'])) {
    // Override the list builder with a version which omits the unused 'Start
    // time' and 'End time' columns.
    $entity_types['site_alert']->setListBuilderClass(JoinupSiteAlertListBuilder::class);
  }
}

/**
 * Implements hook_node_links_alter().
 */
function joinup_core_node_links_alter(array &$links, NodeInterface $entity, array &$context) {
  if (isset($links['comment__field_comments']['#links']['comment-add'])) {
    unset($links['comment__field_comments']['#links']['comment-add']);
  }
  if (isset($links['comment__field_replies']['#links']['comment-add'])) {
    unset($links['comment__field_replies']['#links']['comment-add']);
  }
}

/**
 * Implements hook_field_formatter_info_alter().
 *
 * - Make sure the standard formatter for links can be used for the link that is
 *   used to report inappropriate content.
 */
function joinup_core_field_formatter_info_alter(array &$info) {
  $info['link']['field_types'][] = 'report_link';
}

/**
 * Implements hook_element_info_alter().
 *
 * Override the validate handler for the datetime widget in order to show a
 * custom validation message when part of the widget is not filled in.
 */
function joinup_core_element_info_alter(array &$info) {
  if (isset($info['datetime'])) {
    $info['datetime']['#element_validate'] = [
      [
        Datetime::class,
        'validateDatetime',
      ],
    ];
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 *
 * File entities might have file system redirects coming from previous platform
 * versions, following this pattern (relative to files directory):
 * @code
 * legacy/path/to/image.png -> actual/path/to/image.png
 * @endcode
 * Such redirects are not cleared automatically by the Redirect module, when the
 * source file entity is deleted, thus we're fulfilling this task here.
 */
function joinup_core_file_delete(EntityInterface $entity) {
  /** @var \Drupal\file\FileInterface $entity */
  $uri = $entity->getFileUri();
  $scheme = StreamWrapperManager::getScheme($uri);
  if ($scheme !== 'public') {
    return;
  }

  $path = 'base:/' . \Drupal::service('stream_wrapper.public')->getDirectoryPath() . '/' . StreamWrapperManager::getTarget($uri);

  // Delete all redirects targeting this path.
  redirect_delete_by_path($path);
}

/**
 * Implements hook_editor_js_settings_alter().
 *
 * Strip off the h1, h5, h6 tag format options from the 'Format' dropdown.
 * This does not remove the ability of the user to enter or render these tags.
 *
 * @see https://citnet.tech.ec.europa.eu/CITnet/jira/browse/ISAICP-3682
 */
function joinup_core_editor_js_settings_alter(array &$settings) {
  if (isset($settings['editor']['formats']['content_editor']) && $settings['editor']['formats']['content_editor']['format'] === 'content_editor') {
    $options = explode(';', $settings['editor']['formats']['content_editor']['editorSettings']['format_tags']);
    $options = array_diff($options, ['h1', 'h5', 'h6']);
    $settings['editor']['formats']['content_editor']['editorSettings']['format_tags'] = implode(';', $options);
  }
}

/**
 * Implements hook_ckeditor_css_alter().
 */
function joinup_core_ckeditor_css_alter(array &$css) {
  $css[] = drupal_get_path('module', 'joinup_core') . '/css/wysiwyg.css';
}

/**
 * Implements hook_config_readonly_whitelist_patterns().
 */
function joinup_core_config_readonly_whitelist_patterns() {
  return [
    // The 'support' menu is editable by moderators. This includes the menu
    // links static overrides config.
    'system.menu.support',
    // The outdated content threshold is editable by moderators.
    'joinup_core.outdated_content_threshold',
    'core.menu.static_menu_link_overrides',
  ];
}

/**
 * Implements hook_module_implements_alter().
 */
function joinup_core_module_implements_alter(array &$implementations, $hook) {
  switch ($hook) {
    case 'block_view_system_menu_block_alter':
      // Do not show the contextual links to edit menus. This functionality is
      // used very rarely but the contextual links menu causes visual clutter.
      unset($implementations['menu_ui']);
      break;
  }
}

/**
 * Implements hook_block_access().
 *
 * Determines on which pages to show the Webtools eTrans block. Not all pages
 * are suitable for machine translation.
 *
 * This is handled using a custom access check rather than configuring block
 * visibility conditions in the block UI since we need to check conditions
 * across several domains. This is not possible in the UI because the conditions
 * are compared using "AND" logic.
 *
 * @see https://www.drupal.org/project/drupal/issues/923934
 */
function joinup_core_block_access(BlockInterface $block, string $operation, AccountInterface $account): AccessResultInterface {
  if ($operation === 'view' && $block->id() === 'three_dots_menu') {
    /** @var \Drupal\joinup_core\LocalTaskLinksHelperInterface $local_task_links_helper */
    $local_task_links_helper = \Drupal::service('joinup_core.local_task_links_helper');
    // A local tasks block can be either a horizontal tabs menu or a three-dots
    // menu. Both are not possible on the same page. In order to determine the
    // pages with horizontal tabs, the 'horizontal_tabs' block visibility should
    // be edited. All others pages will show the local tasks as three-dots menu.
    // Avoid the redundancy of maintaining the visibility also for the
    // 'three_dots_menu' block by implementing this hook.
    return $local_task_links_helper->allowThreeDotsMenu();
  }

  if ($operation !== 'view' || $block->getPluginId() !== 'oe_webtools_etrans') {
    return AccessResult::neutral();
  }

  // Check if we are on a route that is suitable for machine translation.
  if (!empty(joinup_core_get_etrans_block_config_for_current_page())) {
    return AccessResult::allowed();
  }
  return AccessResult::forbidden();
}

/**
 * Implements hook_block_build_BASE_BLOCK_ID_alter().
 *
 * Ensures that the Webtools eTrans block varies by route, since we are altering
 * the block configuration depending on the route.
 *
 * @see \joinup_core_block_view_oe_webtools_etrans_alter()
 */
function joinup_core_block_build_oe_webtools_etrans_alter(array &$build, BlockPluginInterface $block) {
  $cacheable_metadata = new CacheableMetadata();
  $cacheable_metadata->addCacheContexts(['route']);
  $cacheable_metadata->applyTo($build);
}

/**
 * Implements hook_block_view_BASE_BLOCK_ID_alter().
 *
 * Tailors the HTML elements that need to be translated by the Webtools eTrans
 * service to the type of the current page.
 */
function joinup_core_block_view_oe_webtools_etrans_alter(array &$build, BlockPluginInterface $block) {
  $block->setConfiguration(joinup_core_get_etrans_block_config_for_current_page() + $block->getConfiguration());
}

/**
 * Returns the Webtools eTrans block configuration for the current page.
 *
 * @return array
 *   The Webtools eTrans block configuration.
 *
 * @see \Drupal\oe_webtools_etrans\Plugin\Block\ETransBlock
 */
function joinup_core_get_etrans_block_config_for_current_page(): array {
  $current_route_name = \Drupal::routeMatch()->getRouteName();
  if (array_key_exists($current_route_name, ETransBlockConfiguration::CONFIG_MAPPING['routes'])) {
    return ETransBlockConfiguration::CONFIG_MAPPING['routes'][$current_route_name];
  }

  /** @var \Drupal\Core\Plugin\Context\ContextRepositoryInterface $context_repository */
  $context_repository = \Drupal::service('context.repository');
  $contexts = $context_repository->getRuntimeContexts(['@node.node_route_context:node']);

  if ($contexts['@node.node_route_context:node']->hasContextValue()) {
    $entity = $contexts['@node.node_route_context:node']->getContextValue();
    foreach (ETransBlockConfiguration::CONFIG_MAPPING['bundles'] as $bundle_class => $config) {
      if ($entity instanceof $bundle_class) {
        return $config;
      }
    }
  }

  return [];
}

/**
 * Implements hook_theme_suggestions_HOOK() for menu_local_task.
 */
function joinup_core_theme_suggestions_menu_local_task(array $variables): array {
  /** @var \Drupal\joinup_core\LocalTaskLinksHelperInterface $local_task_links_helper */
  $local_task_links_helper = \Drupal::service('joinup_core.local_task_links_helper');
  if ($local_task_links_helper->allowHorizontalTabs()->isAllowed()) {
    return ['menu_local_task__horizontal_tabs'];
  }
  return ['menu_local_task__three_dots_menu'];
}

/**
 * Implements hook_entity_bundle_field_info().
 */
function joinup_core_entity_bundle_field_info(EntityTypeInterface $entity_type, string $bundle, array $base_field_definitions): array {
  $fields = [];
  $threshold = \Drupal::config('joinup_core.outdated_content_threshold')->get("{$entity_type->id()}.{$bundle}");
  if ($threshold) {
    $fields['outdated_time'] = BaseFieldDefinition::create('timestamp')
      ->setLabel(t('Outdated time'))
      ->setDescription(t('A date/time when this content will become outdated.'))
      ->setComputed(TRUE)
      ->setRequired(FALSE)
      ->setClass(OutdatedContentFieldItemList::class)
      ->setCardinality(1)
      ->setDefaultValue(NULL);
  }
  return $fields;
}

/**
 * Implements hook_entity_view_alter().
 */
function joinup_core_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display): void {
  if ($entity instanceof OutdatedContentInterface && $display->getMode() === 'default') {
    /** @var \Drupal\Core\Entity\EntityTypeBundleInfoInterface $bundle_info */
    $bundle_info = \Drupal::service('entity_type.bundle.info');
    $bundle_singular_label = $bundle_info->getBundleInfo($entity->getEntityTypeId())[$entity->bundle()]['label_singular'];
    $build['#attached']['drupalSettings']['outdatedContent'] = [
      'outdatedTime' => $entity->getOutdatedTime(),
      'publicationTime' => $entity->getPublicationTime(),
      'bundle' => $bundle_singular_label,
    ];
    $build['#attached']['library'][] = 'joinup_core/outdated_content';

    // Invalidate the cache when the outdated content thresholds are changing.
    (new CacheableMetadata())
      ->addCacheableDependency(\Drupal::config('joinup_core.outdated_content_threshold'))
      ->applyTo($build);
  }
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function joinup_core_menu_local_tasks_alter(&$data, $route_name, RefinableCacheableDependencyInterface &$cacheability) {
  $routes = [
    'entity.node.canonical',
    'entity.rdf_entity.canonical',
    'entity.user.canonical',
  ];
  if (in_array($route_name, $routes) && isset($data['tabs'][0][$route_name])) {
    $data['tabs'][0][$route_name]['#access'] = FALSE;
  }
}
