<?php

/**
 * @file
 * Contains functions and hook implementations for the tallinn module.
 */

define('TALLINN_COMMUNITY_ID', 'http://data.europa.eu/w21/5f4c0dae-f521-4d00-a0cf-e1dce0a128a3');

/**
 * Implements hook_theme().
 */
function tallinn_theme($existing, $type, $theme, $path) {
  return [
    'tallinn_entry_formatter' => [
      'variables' => [
        'title' => '',
        'status' => [],
        'status_classes' => '',
        'explanation' => [],
        'uri' => [],
      ],
    ],
  ];
}
