<?php

/**
 * @file
 * Provides functionality for the Joinup search module.
 */

declare(strict_types = 1);

use Drupal\Component\Utility\Html;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Template\Attribute;
use Drupal\search_api\IndexInterface;
use Drupal\search_api\Query\ConditionGroupInterface;
use Drupal\search_api\Query\QueryInterface;
use Drupal\search_api\Utility\Utility;
use Drupal\views\ViewExecutable;
use Solarium\Core\Query\QueryInterface as SolariumQueryInterface;
use Solarium\QueryType\Select\Query\Query;

/**
 * Implements hook_theme().
 */
function joinup_search_theme($existing, $type, $theme, $path) {
  return [
    'facet_widget_links_inline' => [
      'variables' => [
        'active' => [],
        'items' => [],
        'attributes' => [],
        'prefix_text' => '',
        'suffix_text' => '',
      ],
    ],
    'joinup_search_global_search' => [
      'variables' => ['filters' => [], 'template_suggestion' => ''],
    ],
  ];
}

/**
 * Prepares variables for the facet widget "links inline" template.
 *
 * Default template: facet-widget-links-inline.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - active: an array of active facet items.
 *   - items: an array of inactive facet items.
 *   - attributes: HTML attributes for the main facet wrapper.
 */
function template_preprocess_facet_widget_links_inline(array &$variables) {
  $variables['button_attributes'] = new Attribute([
    'id' => Html::getUniqueId('filter-button'),
    'class' => ['filter__icon', 'icon', 'icon--arrow-down'],
  ]);
}

/**
 * Implements hook_entity_field_access().
 *
 * Grant access to fields of type search only to moderators except from
 * custom_page pages.
 */
function joinup_search_entity_field_access($operation, FieldDefinitionInterface $field_definition, AccountInterface $account, ?FieldItemListInterface $items = NULL) {
  // Limit access to search fields only on edit.
  if ($operation !== 'edit' || $field_definition->getType() !== 'search_api_field') {
    return AccessResult::neutral();
  }

  // Leave open access to the custom page search field.
  if ($field_definition->getTargetEntityTypeId() === 'paragraph' && $field_definition->getName() === 'field_content_listing') {
    return AccessResult::neutral();
  }

  // Forbid access if the user does not have the "administer search fields"
  // permission.
  return AccessResult::forbiddenIf(!$account->hasPermission('administer search fields'))
    ->addCacheContexts(['user.permissions']);
}

/**
 * Implements hook_module_implements_alter().
 */
function joinup_search_module_implements_alter(&$implementations, $hook) {
  if ($hook === 'search_api_query_alter') {
    // The search_api_field_search_api_query_alter is always executed last and
    // is responsible for converting the facets into condition groups. We need
    // to add a sort parameter based on the content bundle on the collection
    // content search api field. Thus, the hook invoked by the collection module
    // should be called last.
    // @see search_api_field_search_api_query_alter
    // @see joinup_search_search_api_query_alter
    $group = $implementations['joinup_search'];
    unset($implementations['joinup_search']);
    $implementations['joinup_search'] = $group;
  }
}

/**
 * Implements hook_search_api_query_alter().
 *
 * Sets a default search ordering for the content displayed in the collections'
 * and solutions' overview page as well as the custom pages.
 *
 * @throws \Drupal\search_api\SearchApiException
 *   Thrown when the Search API server instance could not be loaded.
 */
function joinup_search_search_api_query_alter(QueryInterface $query) {
  if ($query->getSearchId() === 'rdf_entity.field_collection_content') {
    // In case the user has filtered by event, first sort by the event date.
    // @todo This will be generic when event calendar will be implemented for
    // the rdf_entity.field_is_content and the paragraph.field_content_listing
    // instances of the search api field listing.
    if (_joinup_search_search_api_has_condition($query->getConditionGroup(), 'entity_bundle', 'event')) {
      // If the upcoming events are selected, set the order to 'ASC'.
      // @see \Drupal\joinup\Plugin\ArbitraryFacet\EventsArbitraryFacet::getFacetDefinition
      $value = \Drupal::service('facets.utility.date_handler')->isoDate((new DrupalDateTime('today'))->getTimestamp());
      $order = _joinup_search_search_api_has_condition($query->getConditionGroup(), 'field_event_date', $value, '>=') ? QueryInterface::SORT_ASC : QueryInterface::SORT_DESC;
      $query->sort('field_event_date', $order);
    }
  }

  // Sort collection content by creation date, newest first.
  $search_ids = [
    'rdf_entity.field_collection_content',
    'rdf_entity.field_is_content',
    'paragraph.field_content_listing',
  ];

  if (in_array($query->getSearchId(), $search_ids)) {
    $query->sort('entity_created', 'DESC');
  }
}

/**
 * Checks if the query has a filter.
 *
 * @param \Drupal\search_api\Query\ConditionGroupInterface|\Drupal\search_api\Query\ConditionInterface $conditions
 *   A condition group or a condition interface.
 * @param string $field
 *   The field name.
 * @param mixed $value
 *   The requested value. Can be an array but will has to be passed identically.
 * @param string $operator
 *   The requested operator. Defaults to '='.
 *
 * @return bool
 *   True if the condition group has the required condition or false otherwise.
 */
function _joinup_search_search_api_has_condition($conditions, $field, $value, $operator = '=') {
  foreach ($conditions->getConditions() as $c) {
    if ($c instanceof ConditionGroupInterface) {
      if (_joinup_search_search_api_has_condition($c, $field, $value, $operator)) {
        return TRUE;
      }
    }
    elseif ($c->getField() === $field && $c->getValue() === $value && $c->getOperator() === $operator) {
      return TRUE;
    }
  }
  return FALSE;
}

/**
 * Implements hook_search_api_index_items_alter().
 *
 * Do not index any content not written in English.
 */
function joinup_search_search_api_index_items_alter(IndexInterface $index, array &$items): void {
  foreach ($items as $item_id => $item) {
    [, $raw_id] = Utility::splitCombinedId($item_id);
    [, $langcode] = Utility::splitPropertyPath($raw_id);
    // Unset non-english content from the index.
    if ($langcode != 'en') {
      unset($items[$item_id]);
    }
  }
}

/**
 * Implements hook_search_api_solr_documents_alter().
 *
 * By default, solr server configuration has a property named sortMissingLast
 * set to true for all fields defined. This means that two different entity
 * types, one with a property set to false and one without the property, will
 * result in having the one without the property placed last.
 *
 * Set the "sticky" property on all documents that are missing it. The property
 * is prefixed with "bs_" because "b" stands for boolean and "s" for single
 * value, as they are used for sorting.
 */
function joinup_search_search_api_solr_documents_alter(&$documents, IndexInterface $index, array $items) {
  /** @var \Solarium\QueryType\Update\Query\Document\Document[] $documents */
  foreach ($documents as $document) {
    if (empty($document->getFields()['bs_sticky'])) {
      $document->setField('bs_sticky', FALSE);
    }
  }
}

/**
 * Implements hook_search_api_solr_field_mapping_alter().
 *
 * Single value fields need to be used for sorting.
 */
function joinup_search_search_api_solr_field_mapping_alter(IndexInterface $index, array &$fields) {
  $mappings = [
    'entity_created' => 'ds_entity_created',
    'published_on' => 'ds_published_on',
  ];

  foreach ($mappings as $alias => $solr_field) {
    if (isset($fields[$alias])) {
      $fields[$alias] = $solr_field;
    }
  }
}

/**
 * Implements hook_search_api_solr_query_alter().
 */
function joinup_search_search_api_solr_query_alter(SolariumQueryInterface $solarium_query, QueryInterface $query): void {
  if (!$solarium_query instanceof Query) {
    return;
  }

  _joinup_search_apply_global_search_api_solr_settings($solarium_query, $query);
  _joinup_search_apply_listing_content_query_settings($solarium_query, $query);
}

/**
 * Apply the global settings to all solarium queries on Joinup.
 *
 * @param \Solarium\Core\Query\QueryInterface $solarium_query
 *   The solarium query.
 * @param \Drupal\search_api\Query\QueryInterface $query
 *   The search api query class.
 */
function _joinup_search_apply_global_search_api_solr_settings(SolariumQueryInterface $solarium_query, QueryInterface $query): void {
  // Keep the edismax parser to allow document boosting to work properly.
  // @todo remove when document boosting is reimplemented by search_api_solr
  // @see https://citnet.tech.ec.europa.eu/CITnet/jira/browse/ISAICP-4907
  $solarium_query->addParam('defType', 'edismax');

  /** @var \Drupal\search_api_field\Plugin\Field\FieldType\SearchItem $item */
  if (!$item = $query->getOption('search_api_field item')) {
    return;
  }

  $value = $item->value;
  if (empty($value['query_builder']['filters'])) {
    return;
  }

  // Extract all the plugins used.
  $plugin_ids = array_column($value['query_builder']['filters'], 'plugin');
  // If any plugin other than the direct entity reference ones are used,
  // bail out.
  $other_plugins = array_filter($plugin_ids, function ($plugin_id) {
    return strpos($plugin_id, 'bundle_autocomplete:') !== 0;
  });
  if (!empty($other_plugins)) {
    return;
  }

  // Get the real names used to index on Solr.
  /** @var \Drupal\search_api_solr\Plugin\search_api\backend\SearchApiSolrBackend $solr_backend */
  $solr_backend = $query->getIndex()->getServerInstance()->getBackend();
  $solr_fields = $solr_backend->getSolrFieldNames($query->getIndex());

  // Build a sorting function that attributes a weight following the order of
  // the elements in the UI.
  $plugins = array_reverse($value['query_builder']['filters'], TRUE);
  $sort = '';
  foreach ($plugins as $delta => $plugin_config) {
    $field = $plugin_config['field'];
    if (!isset($solr_fields[$field]) || empty($plugin_config['target_id'])) {
      continue;
    }

    if (empty($sort)) {
      $sort = $delta;
      continue;
    }

    $sort = sprintf(
      'if(termfreq(%s,%s),%s,%s)',
      $solr_fields[$field],
      $solarium_query->getHelper()->escapePhrase($plugin_config['target_id']),
      $delta,
      $sort
    );
  }

  $sorts = $solarium_query->getSorts();
  $solarium_query->setSorts([$sort => 'asc'] + $sorts);
}

/**
 * Apply solr settings related to search_api_field listings.
 *
 * @param \Solarium\Core\Query\QueryInterface $solarium_query
 *   The solarium query.
 * @param \Drupal\search_api\Query\QueryInterface $query
 *   The search api query class.
 */
function _joinup_search_apply_listing_content_query_settings(SolariumQueryInterface $solarium_query, QueryInterface $query): void {
  if (!$query->hasTag('search_api_field_field_collection_content') && !$query->hasTag('search_api_field_field_is_content')) {
    return;
  }

  // This alter is aware only about group content searches except when the
  // filter 'event' is applied. When the 'event' filter is applied, the event
  // date is used to sort, in joinup_search_search_api_query_alter().
  // @see joinup_search_search_api_query_alter()
  if (_joinup_search_search_api_has_condition($query->getConditionGroup(), 'entity_bundle', 'event')) {
    return;
  }

  /** @var \Drupal\Core\Entity\EntityInterface $entity */
  if (!$entity = $query->getOption('search_api_field entity')) {
    return;
  }

  // In order to sort by the pinned status of the entity, we need to create a
  // sort function query. The values that are used for sort are evaluated at
  // runtime instead of being retrieved from the index.
  // An entity is pinned when:
  // - for nodes, when they are belong to the current group and the sticky
  //   field is set to true;
  // - for solutions, when they are pinned inside the current collection.
  // The query() Solr function query is a good candidate for doing custom sorts,
  // but it will return the score of the subquery. The score can be different
  // between single results and can range from a small fraction above zero to
  // infinite.
  // Example:
  // @codingStandardsIgnoreStart
  // "or(and(bs_sticky, query({!v='sm_entity_groups:<id>'},0)), query({!v='sm_rdf_pinned_in:<id>'},0))"
  // "query({!v='(bs_sticky:true AND sm_entity_groups:<id>) OR (sm_rdf_pinned_in:<id>)'})"
  // @codingStandardsIgnoreEnd
  // The and() operator will return false when the subquery score is lower than
  // 1, so both of the above will fail the sorting.
  // Solr 6.x has the gt(x,y) function, that will return true if x is greater
  // than y. By using gt(), any positive score can be transformed to true.
  // Example:
  // @codingStandardsIgnoreStart
  // "or(and(bs_sticky, gt(query({!v='sm_entity_groups:<id>'},0),0)), gt(query({!v='sm_rdf_pinned_in:<id>'},0),0))"
  // "gt(query({!v='(bs_sticky:true AND sm_entity_groups:<id>) OR (sm_rdf_pinned_in:<id>)'}),0)"
  // @codingStandardsIgnoreEnd
  // Unfortunately, Solr 5.x doesn't support the gt() function.
  // Both Solr versions support the termfreq() function, which will return the
  // number of occurrences of a term in a field of the document.
  // Alternatively, also the exists() function could be used in conjunction with
  // the query() function, but it looks more expensive.
  // Example:
  // @codingStandardsIgnoreLine
  // "or(and(bs_sticky,exists(query({!v='sm_entity_groups:<id>'},0))),exists(query({!v='sm_rdf_pinned_in:<id>'},0)))"
  // @see https://lucene.apache.org/solr/guide/6_6/function-queries.html#function-queries
  // @see http://archive.apache.org/dist/lucene/solr/ref-guide/apache-solr-ref-guide-5.5.pdf
  $computed_sort = sprintf(
    "or(termfreq(sm_node_pinned_in,%1\$s),termfreq(sm_rdf_pinned_in,%1\$s))",
    $solarium_query->getHelper()->escapePhrase($entity->id())
  );
  $solarium_query->setSorts([
    $computed_sort => 'desc',
    'score' => 'desc',
    'ds_entity_created' => 'desc',
  ]);
}

/**
 * Implements hook_views_pre_execute().
 */
function joinup_search_views_pre_execute(ViewExecutable $view) {
  if ($view->id() !== 'search') {
    return;
  }

  // Having exposed sort options mean that only one option is passed in the
  // query. Regardless of the case, add the entity_created as a secondary sort
  // method to ensure legacy support.
  // Selecting the entity_created option itself won't affect the query.
  $view->getQuery()->sort('entity_created', 'DESC');
}

/**
 * Implements hook_theme_suggestions_HOOK_alter() for the global search block.
 *
 * Includes the template suggestion that can be configured in the block settings
 * for the global search block.
 */
function joinup_search_theme_suggestions_joinup_search_global_search(array $variables): array {
  if (!empty($variables['template_suggestion'])) {
    return ['joinup_search_global_search__' . $variables['template_suggestion']];
  }

  return [];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function joinup_search_form_facets_form_alter(array &$form, FormStateInterface $form_state, string $form_id): void {
  if (isset($form['facets']['topic']) && isset($form['facets']['topic'][0])) {
    $form['facets']['topic'][0]['topic']['#slim_select'] = ['showSearch' => TRUE];
  }
}
