<?php

/**
 * @file
 * Provides functionality for the contact information module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function contact_information_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {
  if ($entity_type->id() == 'rdf_entity' && $bundle == 'contact_information' && !empty($fields['field_ci_email'])) {
    $fields['field_ci_email']->addConstraint('JoinupEmail');
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function contact_information_rdf_entity_presave(EntityInterface $entity) {
  // Handle only contact information entities.
  if ($entity->bundle() != 'contact_information') {
    return;
  }

  // Generate the label using the values of the name field.
  $names = array_column($entity->get('field_ci_name')->getValue(), 'value');
  $entity->set('label', implode(', ', $names));
}
