<?php
/**
 * @file
 * Main functions and hook implementations of the RDF Taxonomy module.
 */

use \Drupal\Core\Form\FormStateInterface;
use \Drupal\taxonomy\Entity\Vocabulary;

/**
 * Implements hook_entity_type_alter().
 *
 * Set the controller class for vocabularies and terms to an alternate
 * implementation of the Drupal\Core\Entity\EntityStorageInterface interface.
 */
function rdf_taxonomy_entity_type_alter(array &$entity_types) {
  $entity_types['taxonomy_vocabulary']->setStorageClass('Drupal\rdf_taxonomy\VocabularyRdfStorage');
  $entity_types['taxonomy_term']->setStorageClass('Drupal\rdf_taxonomy\TermRdfStorage');
  $entity_types['taxonomy_term']->setHandlerClass('views_data', NULL);
}

/**
 * Implements hook_form_alter().
 */
function rdf_taxonomy_form_taxonomy_vocabulary_form_alter(&$form, FormStateInterface $form_state) {
  // Only add mapping form element to rdf entities fields.
  if ($form_state->get('entity_type_id') != 'rdf_entity') {
    //return;
  }
  $form_obj = $form_state->getFormObject();
  /** @var \Drupal\taxonomy\Entity\Vocabulary $entity */
  $entity = $form_obj->getEntity();
  // $schema = $entity->getSchema();
  $form['rdf_mapping'] = array(
    '#type' => 'details',
    '#title' => t('Vocabulary id'),
    '#description' => t('skos:ConceptScheme'),
    '#weight' => 99,
    '#open' => TRUE,
  );
  $form['rdf_mapping']['concept_scheme'] = array(
    '#type' => 'textfield',
    '#title' => 'skos:ConceptScheme URI used to query the vocabulary',
    '#weight' => 150,
    '#default_value' => $entity->getThirdPartySetting('rdf_entity', 'ConceptScheme', FALSE),
    '#required' => TRUE,
  );

  $form['#entity_builders'][] = 'rdf_taxonomy_form_alter_builder';
}

/**
 * Entity builder callback: Save rdf field mapping.
 */
function rdf_taxonomy_form_alter_builder($entity_type, Vocabulary $entity, array &$form, FormStateInterface $form_state) {
    $value = $form_state->getValue('concept_scheme');
    $entity->setThirdPartySetting('rdf_entity', 'ConceptScheme', $value);
}


/**
 * Implements hook_bundle_mapping_alter().
 */
function rdf_taxonomy_bundle_mapping_alter(&$mapping) {
  foreach (\Drupal::entityTypeManager()->getStorage('taxonomy_vocabulary')->loadMultiple() as $entity) {
    $mapping['taxonomy_term']['http://www.w3.org/2004/02/skos/core#Concept'] = $entity->id();
  }
}