/**
 * @file
 * Makes the collection last update time dynamic and cacheable.
 */

(function ($, Drupal, drupalSettings) {

  /**
   * Makes the collection last update time dynamic and cacheable.
   *
   * We use the timeago jquery plugin (http://timeago.yarp.com) to replace the
   * formatted date with a "time ago" string. We don't return a "time ago" from
   * server because that value is changing very often (every second), meaning
   * that we cannot cache the value and, as an effect, the whole page will
   * become uncacheable. Instead we display the formatted last update time and
   * then, in JS enabled browsers, we replace the formatted date/time with a
   * "time ago" expression that is generated by plugin. The value rendered by
   * the plugin is refreshed each minute.
   *
   * @type {Drupal~behavior}
   *
   * @prop {Drupal~behaviorAttach} attach
   *   Uses timeago jquery plugin for 'last_update_timestamp' formatter.
   *
   * @see http://timeago.yarp.com
   */
  Drupal.behaviors.collectionLastUpdateTime = {
    attach: function (context) {
      // Merge the custom settings.
      $.extend(true, $.timeago.settings,
        drupalSettings.collection.timeagoSettings
      );
      $('time.js-collection-last-update').timeago();
    }
  };

})(jQuery, Drupal, drupalSettings);
