condition.plugin.eif_solutions_page:
  type: condition.plugin
  label: 'EIF Solutions condition plugin'
  mapping:
    eif_solutions:
      type: boolean
      label: 'EIF Solution'

views.argument_validator.eif_toolbox:
  type: views.argument_validator_entity
  label: 'EIF Toolbox argument validator'
