<?php

namespace Drupal\joinup\Plugin\ArbitraryFacet;

use Drupal\search_api_arbitrary_facet\Plugin\ArbitraryFacetBase;

/**
 * Provides supports for facets generated by arbitrary queries.
 *
 * @ArbitraryFacet(
 *   id = "events_arbitrary",
 *   label = @Translation("Future/My/Past events"),
 * )
 */
class EventsArbitraryFacet extends ArbitraryFacetBase {

  /**
   * {@inheritdoc}
   */
  public function getFacetDefinition() {
    $current_user = \Drupal::currentUser();

    $definition = [
      'future_events' => [
        'field_name' => 'field_event_date',
        'field_condition' => '[NOW TO *]',
        'label' => $this->t('Future events'),
      ],
    ];

    if (!$current_user->isAnonymous()) {
      $definition['my_events'] = [
        'field_name' => 'entity_author',
        'field_condition' => $current_user->id(),
        'label' => $this->t('My events'),
      ];
    }

    $definition += [
      'past_events' => [
        'field_name' => 'field_event_date',
        'field_condition' => '[* TO NOW]',
        'label' => $this->t('Past events'),
      ],
    ];

    return $definition;
  }

}
