<?php

namespace Drupal\joinup\Plugin\ArbitraryFacet;

use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\search_api_arbitrary_facet\Plugin\ArbitraryFacetBase;

/**
 * Provides supports for facets generated by arbitrary queries.
 *
 * @ArbitraryFacet(
 *   id = "events_arbitrary",
 *   label = @Translation("Future/My/Past events"),
 * )
 */
class EventsArbitraryFacet extends ArbitraryFacetBase {

  /**
   * {@inheritdoc}
   */
  public function getFacetDefinition() {
    $current_user = \Drupal::currentUser();
    // Yesterday midnight translates to yesterday's 24:00:00 which is today's
    // 00:00:00. This will put today's events to the list of upcoming events.
    $today_midnight = DrupalDateTime::createFromTimestamp(strtotime('yesterday midnight'))->format('Y-m-d\Th:m:i\Z');
    $definition = [
      'upcoming_events' => [
        'field_name' => 'field_event_date',
        'field_condition' => $today_midnight,
        'field_operator' => '>=',
        'label' => $this->t('Upcoming events'),
      ],
    ];

    if (!$current_user->isAnonymous()) {
      $definition['my_events'] = [
        'field_name' => 'entity_author',
        'field_condition' => $current_user->id(),
        'label' => $this->t('My events'),
      ];
    }

    $definition += [
      'past_events' => [
        'field_name' => 'field_event_date',
        'field_condition' => $today_midnight,
        'field_operator' => '<=',
        'label' => $this->t('Past events'),
      ],
    ];

    return $definition;
  }

}
