action.configuration.joinup_og_membership_delete_action:
  type: action_configuration_default
  label: 'Delete the selected membership(s) config'

action.configuration.joinup_transfer_group_ownership:
  type: action_configuration_default
  label: 'Transfer the ownership of the group to the selected member'

# Schema for the group sidebar menu block settings.
block.settings.group_menu_block:*:
  type: group_menu_block_default
  label: 'Group sidebar menu block settings'

# Default schema for group menu block settings.
group_menu_block_default:
  type: block_settings
  label: 'Og menu block settings'
  mapping:
    level:
      type: integer
      label: 'Starting level'
    depth:
      type: integer
      label: 'Maximum number of levels'

views.argument.search_api_group:
  type: views.argument.search_api
  label: 'Search API group'

views.argument_default.rdf_entity:
  type: mapping
  label: 'RDF entity'
  mapping:
    parameter_name:
      type: string
      label: 'Parameter name'
