<?php

/**
 * @file
 * Contains joinup_migrate.module.
 */

use Drupal\Core\Database\Query\AlterableInterface;
use Drupal\joinup_migrate\Plugin\migrate\source\JoinupSqlBase;

/**
 * Implements hook_query_TAG_alter().
 *
 * Alters queries tagged with 'uri' by LEFT JOINing to {content_field_id_uri}
 * table and adding the uri field to the query as 'uri'.
 */
function joinup_migrate_query_uri_alter(AlterableInterface $query) {
  $alias = $query->getMetaData('alias');
  $source_db = JoinupSqlBase::getSourceDbName();
  $alias['uri'] = $query->leftJoin("$source_db.content_field_id_uri", 'uri', "{$alias['node']}.vid = %alias.vid");
  // Save back aliases.
  $query->addMetaData('alias', $alias);
  $query->addExpression("TRIM({$alias['uri']}.field_id_uri_value)", 'uri');
}
