<?php

/**
 * @file
 * Contains joinup_migrate.module.
 */

use Drupal\Core\Database\Query\AlterableInterface;

/**
 * Implements hook_query_TAG_alter().
 *
 * Alters queries tagged with 'uri' by LEFT JOINing to {content_field_id_uri}
 * table and adding the uri field to the query as 'uri'.
 */
function joinup_migrate_query_uri_alter(AlterableInterface $query) {
  /** @var \Drupal\Core\Database\Query\SelectInterface $query */
  $alias = $query->getMetaData('alias');
  $alias['uri'] = $query->leftJoin('content_field_id_uri', 'uri', "{$alias['node']}.vid = %alias.vid");
  // Save back aliases.
  $query->addMetaData('alias', $alias);
  $query->addExpression("TRIM({$alias['uri']}.field_id_uri_value)", 'uri');
}
