<?php

/**
 * @file
 * Hook implementations for og_comment.
 */

declare(strict_types = 1);

/**
 * Implements hook_entity_type_alter().
 */
function og_comment_entity_type_alter(array &$entity_types) {
  /** @var Drupal\Core\Entity\ContentEntityType $comment */
  $comment = $entity_types['comment'];
  // Swap out access handler for comments.
  $comment->setAccessClass('Drupal\og_comment\OgCommentAccessControlHandler');
}
