<?php

/**
 * @file
 * Contains functions for the Joinup front page module.
 */

declare(strict_types = 1);

/**
 * @file
 * Contains the main functionality of Joinup front page module.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function joinup_front_page_form_menu_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\system\Entity\Menu $menu */
  $menu = $form_state->getFormObject()->getEntity();
  if ($menu->id() !== 'front-page') {
    return;
  }

  foreach ($form['links']['links'] as $plugin_id => $link_data) {
    if (is_array($form['links']['links'][$plugin_id]) && isset($form['links']['links'][$plugin_id]['operations']['#links']['edit'])) {
      // The user does not have access to the edit form anyway.
      unset($form['links']['links'][$plugin_id]['operations']['#links']['edit']);
    }
  }
}

/**
 * Implements hook_entity_view_alter().
 */
function joinup_front_page_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if (in_array($entity->getEntityTypeId(), ['node', 'rdf_entity'])) {
    $front_page_helper = \Drupal::service('joinup_front_page.front_page_helper');
    $menu_item = $front_page_helper->getFrontPageMenuItem($entity);

    // Add the "entity" contextual links group.
    $build['#contextual_links']['entity'] = [
      'route_parameters' => [
        'entity_type' => $entity->getEntityTypeId(),
        'entity' => $entity->id(),
      ],
      'metadata' => ['changed' => $entity->getChangedTime()],
    ];

    $build['#contextual_links']['entity']['metadata']['is_site_wide_pinned'] = (int) !empty($menu_item);
  }
}
