<?php

/**
 * @file
 * Hook implementations for the Joinup front page module.
 */

declare(strict_types = 1);

/**
 * Implements hook_preprocess_HOOK().
 *
 * The 'Discover topics' block which is shown on the front page is created using
 * the Views module. The block includes a 'See more topics' link which opens a
 * modal dialog with the full list of available topics. Include the necessary JS
 * so that all users can interact with the modal.
 */
function joinup_front_page_preprocess_block(&$variables): void {
  if (!isset($variables['derivative_plugin_id']) || $variables['derivative_plugin_id'] !== 'discover_topics-block') {
    return;
  }

  // Load the library.
  $variables['#attached']['library'][] = 'core/jquery';
  $variables['#attached']['library'][] = 'core/drupal.dialog.ajax';
}

/**
 * Implements hook_theme().
 */
function joinup_front_page_theme(): array {
  return [
    'explore_block' => [
      'variables' => [
        'data' => [],
      ],
    ],
  ];
}
