<?php

/**
 * @file
 * Hook implementations for the Joinup front page module.
 */

declare(strict_types = 1);

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function joinup_front_page_form_menu_edit_form_alter(&$form, FormStateInterface $form_state, $form_id): void {
  /** @var \Drupal\system\Entity\Menu $menu */
  $menu = $form_state->getFormObject()->getEntity();
  if ($menu->id() !== 'front-page') {
    return;
  }

  $form['#title'] = t('Front page pinned items');
  $form['links']['links']['#empty'] = t('There are no pinned items. Start by pinning an entity to the front page.');

  foreach ($form['links']['links'] as &$link_data) {
    if (is_array($link_data) && isset($link_data['#item'])) {
      // The user does not have access to the edit form anyway.
      unset($link_data['operations']['#links']['edit']);

      // Disallow nesting for all entries.
      $link_data['#attributes']['class'][] = 'tabledrag-root';
      $link_data['#attributes']['class'][] = 'tabledrag-leaf';
    }
  }
}
