<?php

/**
 * @file
 * Hook implementations for the Joinup Stats test module.
 */

declare(strict_types = 1);

use Drupal\joinup_stats_test\Entity\AssetDistribution;
use Drupal\joinup_stats_test\Entity\CommunityContent;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function joinup_stats_test_entity_bundle_info_alter(&$bundles) {
  foreach (['discussion', 'document', 'event', 'news'] as $bundle) {
    if (!empty($bundles['node'][$bundle])) {
      $bundles['node'][$bundle]['class'] = CommunityContent::class;
    }
  }
  if (!empty($bundles['rdf_entity']['asset_distribution'])) {
    $bundles['rdf_entity']['asset_distribution']['class'] = AssetDistribution::class;
  }
}
