<?php

/**
 * @file
 * Primary module hooks for Joinup pipeline logging module.
 */

declare(strict_types = 1);

use Drupal\user\UserInterface;

/**
 * Implements hook_user_login().
 */
function joinup_pipeline_log_user_login(UserInterface $account) {
  if (!$account->hasPermission('access pipeline selector')) {
    // If the user does not have access to run a pipeline, they should not
    // receive warnings about them either.
    return;
  }
  $time = \Drupal::getContainer()->get('datetime.time');
  $pipeline_manager = \Drupal::getContainer()->get('plugin.manager.pipeline_pipeline');
  $interval = \Drupal::getContainer()->get('config.factory')->get('joinup_pipeline_log.settings')->get('last_run_interval');
  foreach (\Drupal::getContainer()->get('keyvalue')->get('joinup_pipeline_log')->getAll() as $pipeline_id => $last_execute) {
    if (!$account->hasPermission("execute {$pipeline_id} pipeline")) {
      // Only show information about pipelines they have the ability to execute.
      continue;
    }

    $time_since_last_run = $time->getRequestTime() - $last_execute;
    if ($time_since_last_run >= $interval) {
      $pipeline = $pipeline_manager->getDefinition($pipeline_id);
      Drupal::messenger()->addWarning(t('Pipeline :pipeline has not been executed for :days days.', [
        ':pipeline' => $pipeline['label'],
        // Convert to days.
        ':days' => floor($time_since_last_run / 86400),
      ]));
    }
  }
}
