<?php

/**
 * Helper script to clean up the old db .
 */
$servername = "localhost";
$username = "";
$password = "";
$dbname = "";

// Create connection
$link = mysqli_connect( $servername, $username, $password ) or die( mysqli_error($link) );
mysqli_select_db( $link, $dbname ) or die( mysqli_error($link) );

// Truncate tables not needed during the migration.
foreach (truncate_tables() as $table) {
  $sql = "TRUNCATE $table";
  print $sql . "\n";
  $result = mysqli_query($link, $sql);
}

// Delete old revision data and orphan entries.
foreach (content_tables() as $table) {
  print "Cleaning $table\n";
  $sql = "DELETE f FROM $table as f JOIN node ON node.nid = f.nid WHERE f.vid != node.vid;";
  $result = mysqli_query($link, $sql);
  $sql = "DELETE f FROM $table as f JOIN node ON node.nid = f.nid WHERE node.nid IS NULL;";
  $result = mysqli_query($link, $sql);
}

// Delete old revision data and orphan entries from terms.
$sql = "DELETE t FROM term_node AS t JOIN node ON t.nid = node.nid WHERE t.vid <> node.vid;";
$result = mysqli_query($link, $sql);
$sql = "DELETE t FROM term_node AS t JOIN node ON t.nid = node.nid WHERE node.nid IS NULL;";
$result = mysqli_query($link, $sql);

// Delete old revision data and orphan entries from statistics.
$sql = "DELETE t FROM isa_download_statistics AS i JOIN node ON i.nid = node.nid WHERE node.nid IS NULL;";
$result = mysqli_query($link, $sql);

function truncate_tables() {
  return [
    'access',
    'accesslog',
    'advagg_bundles',
    'advagg_files',
    'apachesolr_attachments_files',
    'apachesolr_search_node',
    'autoload_registry',
    'autoload_registry_file',
    'backup_migrate_destinations',
    'backup_migrate_profiles',
    'backup_migrate_schedules',
    'batch',
    'blocks',
    'blocks_roles',
    'boxes',
    'cache',
    'cache_admin_menu',
    'cache_advagg',
    'cache_advagg_bundle_reuse',
    'cache_advagg_files_data',
    'cache_apachesolr',
    'cache_block',
    'cache_content',
    'cache_emfield_xml',
    'cache_filter',
    'cache_form',
    'cache_htmlpurifier',
    'cache_media_youtube_status',
    'cache_menu',
    'cache_page',
    'cache_project_release',
    'cache_rules',
    'cache_views',
    'cache_views_data',
    'captcha_points',
    'captcha_sessions',
    'commit_management',
    'conditional_fields',
    'context',
    'ctools_css_cache',
    'ctools_object_cache',
    'devel_queries',
    'devel_times',
    'epractice_files',
    'epractice_url_alias',
    'filefield_paths',
    'files_paths',
    'flag_content',
    'flag_counts',
    'flag_types',
    'flags',
    'flexifield_items',
    'flood',
    'freelinking',
    'heartbeat_activity',
    'heartbeat_comments',
    'heartbeat_messages',
    'heartbeat_mt',
    'heartbeat_tags',
    'heartbeat_translations',
    'history',
    'homebox_pages',
    'homebox_users',
    'honeypot_user',
    'imagecache_action',
    'imagecache_preset',
    'listhandler',
    'listhandler_prefix',
    'locales_source',
    'locales_target',
    'menu_links',
    'menu_router',
    'migrate_log',
    'migrate_map_epracticeblog',
    'migrate_map_epracticecase',
    'migrate_map_epracticecommunity',
    'migrate_map_epracticecommunityresource',
    'migrate_map_epracticeedocument',
    'migrate_map_epracticeelibrary',
    'migrate_map_epracticeevents',
    'migrate_map_epracticenews',
    'migrate_map_epracticeprofile',
    'migrate_map_epracticeresource',
    'migrate_map_epracticetaxonomy',
    'migrate_map_epracticetv',
    'migrate_map_epracticeuser',
    'migrate_map_epracticeusercommunityrelation',
    'migrate_map_epracticeworkshop',
    'migrate_map_joinupcase',
    'migrate_message_epracticeblog',
    'migrate_message_epracticecase',
    'migrate_message_epracticecommunity',
    'migrate_message_epracticecommunityresource',
    'migrate_message_epracticeedocument',
    'migrate_message_epracticeelibrary',
    'migrate_message_epracticeevents',
    'migrate_message_epracticenews',
    'migrate_message_epracticeprofile',
    'migrate_message_epracticeresource',
    'migrate_message_epracticetaxonomy',
    'migrate_message_epracticetv',
    'migrate_message_epracticeuser',
    'migrate_message_epracticeusercommunityrelation',
    'migrate_message_epracticeworkshop',
    'migrate_message_joinupcase',
    'migrate_status',
    'node_access',
    'node_comment_statistics',
    'node_counter',
    'node_spambot',
    'password_policy',
    'password_policy_expiration',
    'password_policy_force_change',
    'password_policy_history',
    'password_policy_role',
    'project_issue_categories',
    'project_issue_comments',
    'project_issue_projects',
    'project_issue_state',
    'project_package_local_release_item',
    'project_projects',
    'project_release_file',
    'project_release_nodes',
    'project_release_package_errors',
    'project_release_projects',
    'project_release_supported_versions',
    'project_subscriptions',
    'qa_answer',
    'qa_question',
    'queue',
    'repositories_management',
    'rules_rules',
    'rules_scheduler',
    'rules_sets',
    'search_dataset',
    'search_index',
    'search_node_links',
    'search_total',
    'semaphore',
    'sessions',
    'subscriptions',
    'subscriptions_last_sent',
    'subscriptions_queue',
    'subscriptions_user',
    'trigger_assignments',
    'tvi_settings',
    'userpoints_txn',
    'variable',
    'views_display',
    'views_object_cache',
    'views_view',
    'votingapi_cache',
    'votingapi_vote',
    'watchdog',
    'web_directories',
    'xmlsitemap',
    'xmlsitemap_sitemap',
  ];
}

function content_tables() {
  return [
    'node_revisions',
    'content_type_adms_software_project',
    'content_type_advertisement',
    'content_type_advpoll_binary',
    'content_type_analytical_model',
    'content_type_asset_node_reference',
    'content_type_asset_release',
    'content_type_blog',
    'content_type_case_epractice',
    'content_type_catalogue_node',
    'content_type_checksum',
    'content_type_community',
    'content_type_contact_point',
    'content_type_contexthelp',
    'content_type_data_set',
    'content_type_distribution',
    'content_type_document',
    'content_type_documentation',
    'content_type_event',
    'content_type_factsheet',
    'content_type_featured_catalogue',
    'content_type_federated_forge',
    'content_type_federated_project',
    'content_type_home_carousel',
    'content_type_home_catalogue',
    'content_type_identifier',
    'content_type_image',
    'content_type_isa_camss_assessment',
    'content_type_language_textarea',
    'content_type_language_textfield',
    'content_type_licence',
    'content_type_news',
    'content_type_og_page',
    'content_type_presentation',
    'content_type_profile',
    'content_type_project_issue',
    'content_type_project_project',
    'content_type_project_release',
    'content_type_publisher',
    'content_type_repository',
    'content_type_software_identifier',
    'content_type_software_project_agent',
    'content_type_software_release_agent',
    'content_type_topic',
    'content_type_video',
    'content_type_wiki',
    'content_field_additional_doc_desc',
    'content_field_additional_doc_file',
    'content_field_asset_alternative_name',
    'content_field_asset_assessment',
    'content_field_asset_description',
    'content_field_asset_distribution',
    'content_field_asset_documentation',
    'content_field_asset_identifier',
    'content_field_asset_last_modification',
    'content_field_asset_name',
    'content_field_asset_node_reference',
    'content_field_asset_publisher',
    'content_field_asset_sw_metrics',
    'content_field_asset_temporal_coverage',
    'content_field_asset_version',
    'content_field_asset_webpage_doc',
    'content_field_autotag',
    'content_field_case_documentation',
    'content_field_case_sector',
    'content_field_city',
    'content_field_contact_point_address',
    'content_field_contact_point_mail',
    'content_field_contact_point_name',
    'content_field_contact_point_telephone',
    'content_field_contact_point_web_page',
    'content_field_country',
    'content_field_data_set_name',
    'content_field_distribution_access_url1',
    'content_field_distribution_description',
    'content_field_distribution_download_url',
    'content_field_distribution_licence',
    'content_field_distribution_name',
    'content_field_distribution_publisher',
    'content_field_documentation',
    'content_field_documentation_title',
    'content_field_email',
    'content_field_event_documentation',
    'content_field_factsheet_upload_files',
    'content_field_id_uri',
    'content_field_image',
    'content_field_languages_fields',
    'content_field_language_textfield_lang',
    'content_field_licence_description',
    'content_field_licence_name',
    'content_field_node_catalogue',
    'content_field_presentation_upload_files',
    'content_field_profile_sector',
    'content_field_project_common_contact',
    'content_field_project_common_type',
    'content_field_project_common_using',
    'content_field_project_issues_attachement',
    'content_field_project_soft_features',
    'content_field_project_soft_future_plans',
    'content_field_project_soft_get_involved',
    'content_field_project_soft_logo',
    'content_field_project_soft_more_lin',
    'content_field_project_soft_more_links',
    'content_field_project_soft_public_admin',
    'content_field_project_soft_sponsor_logo',
    'content_field_publication_date',
    'content_field_publisher',
    'content_field_publisher_name',
    'content_field_release_document',
    'content_field_repository_asset_reference',
    'content_field_repository_contact_point',
    'content_field_repository_description',
    'content_field_repository_name',
    'content_field_repository_publisher',
    'content_field_repository_schema',
    'content_field_repository_url',
    'content_field_shared_is_eu_initiative',
    'content_field_shared_tis_image',
    'content_field_shared_tis_teaser',
    'content_field_show_title',
    'content_field_sw_project_agent_nam',
    'content_field_sw_project_agents',
    'content_field_sw_project_agent_type',
    'content_field_sw_project_bug_database',
    'content_field_sw_project_description',
    'content_field_sw_project_logo',
    'content_field_sw_project_metrics',
    'content_field_sw_project_name',
    'content_field_sw_project_repository',
    'content_field_sw_project_wiki',
    'content_field_sw_release',
    'content_field_sw_release_agent_name',
    'content_field_sw_release_agent_type',
    'content_field_top_title',
  ];
}
