# Development configs and commands

commands:

  # Downloads all backends backups.
  dev:download-databases:
    - { task: "run", command: "mysql:download-dump" }
    - { task: "run", command: "virtuoso:download-snapshot" }
    - { task: "run", command: "solr:download-snapshot" }

  # Restores all backends from backup.
  dev:restore-databases:
    - task: run
      command: solr:restore
    - task: run
      command: virtuoso:restore
    - task: exec
      command: ${phing.bin}
      arguments:
        - disable-webtools-geocoding-cache
    - task: run
      command: toolkit:install-dump

  # Rebuilds the dev environment.
  dev:rebuild-environment:
    - task: run
      command: dev:restore-databases
    - task: run
      command: toolkit:run-deploy
