contact_information.settings:
  type: config_object
  label: 'Contact information workflow permission settings'
  mapping:
    transitions:
      label: 'Allowed transitions'
      type: sequence
      sequence:
        label: 'Target state'
        type: sequence
        sequence:
          label: 'Source state'
          type: contact_information.workflow_ownership_settings

contact_information.workflow_ownership_settings:
  label: 'Ownership settings'
  type: mapping
  mapping:
    own:
      label: 'Own content'
      type: contact_information.workflow_role_settings
    any:
      label: 'Any content'
      type: contact_information.workflow_role_settings

contact_information.workflow_role_settings:
  label: 'Role settings'
  type: mapping
  mapping:
    roles:
      label: 'System roles'
      type: sequence
      sequence:
        label: 'Role id'
        type: string
    og_roles:
      label: 'Og roles'
      type: sequence
      sequence:
        label: 'Role id'
        type: string
