# Extend the default search_api_field schema to add the "show_shared" key.
field.field.node.custom_page.field_cp_content_listing:
  type: field_config_base
  label: 'Field'
  mapping:
    default_value:
      type: sequence
      label: 'Default values'
      sequence:
        type: field.value.[%parent.%parent.field_type]
        label: 'Default value'
        mapping:
          value:
            type: mapping
            label: 'Value'
            mapping:
              fields:
                type: sequence
                label: 'Field name'
                sequence:
                  type: mapping
                  mapping:
                    weight:
                      type: integer
                      label: 'Weight'
                    region:
                      type: string
                      label: 'Region'
              enabled:
                type: integer
                label: 'Enabled'
              query_presets:
                type: string
                label: 'Query presets'
              limit:
                type: integer
                label: 'Limit'
              show_shared:
                type: boolean
                label: 'Show shared'
              query_builder:
                type: mapping
                label: 'Query builder'
                mapping:
                  filters:
                    type: sequence
                    label: 'Filters'
                    sequence:
                      type: search_api_field.plugin.filter.[plugin]

field.widget.settings.search_api_field_custom_page:
  type: field.widget.settings.search_api_field_default

# Schema for the TOC menu block settings.
block.settings.custom_page_toc:*:
  type: group_menu_block_default
  label: 'TOC menu block settings'
