# Development configs and commands

phpstan:
  bin: ${joinup.dir}/vendor/bin/phpstan

dev:
  modules:
    - admin_toolbar
    - cas_mock_server
    - config_devel
    - config_update
    - dblog
    - joinup_default_content
    - devel
    - field_ui
    - filecache
    - joinup_cas_mock_server
    - page_manager_ui
    - views_ui

commands:

  # Downloads all backends backups.
  dev:download-databases:
    - { task: "run", command: "mysql:download-dump" }
    - { task: "run", command: "virtuoso:download-snapshot" }
    - { task: "run", command: "solr:download-snapshot" }

  # Restores all backends from backup.
  dev:restore-databases:
    - task: run
      command: solr:restore
    - task: run
      command: virtuoso:restore
    - task: run
      command: drupal:settings
      arguments:
        - site-clone
    - task: run
      command: toolkit:install-dump

  # Rebuilds the dev environment by restoring backups and applying updates.
  dev:rebuild-environment:
    - task: run
      command: solr:restore
    - task: run
      command: virtuoso:restore
    - task: run
      command: redis:flush-all
    - task: run
      command: drupal:settings
      arguments:
        - site-clone
    - task: run
      command: toolkit:install-clone
    - task: exec
      command: ${drush.bin}
      arguments:
        - php:eval
        - if (node_access_needs_rebuild()) { node_access_rebuild(); }

  dev:install-modules:
    - task: run
      command: config-readonly:disable
    - task: run
      command: drush:module-install
      arguments: ${dev.modules}
    - task: run
      command: config-readonly:enable

  dev:demo-users:
    - task: run
      command: config-readonly:disable
    # Make sure CAS mock server module is installed.
    - task: run
      command: drush:module-install
      arguments: cas_mock_server
    - task: exec
      command: ${drush.bin}
      arguments:
        - user:create
        - administrator
      options:
        mail: administrator@example.com
        password: administrator
        yes: null
        root: ${joinup.site_dir}
    - task: exec
      command: ${drush.bin}
      arguments:
        - user:role:add
        - administrator
        - administrator
      options:
        yes: null
        root: ${joinup.site_dir}
    - task: exec
      command: ${drush.bin}
      arguments:
        - cas-mock-server:user-create
        - administrator
      options:
        email: administrator@example.com
        password: administrator
        yes: null
        root: ${joinup.site_dir}
    - task: exec
      command: ${drush.bin}
      arguments:
        - cas:set-cas-username
        - administrator
        - administrator
      options:
        yes: null
        root: ${joinup.site_dir}
    - task: exec
      command: ${drush.bin}
      arguments:
        - user:create
        - moderator
      options:
        mail: moderator@example.com
        password: moderator
        yes: null
        root: ${joinup.site_dir}
    - task: exec
      command: ${drush.bin}
      arguments:
        - user:role:add
        - moderator
        - moderator
      options:
        yes: null
        root: ${joinup.site_dir}
    - task: exec
      command: ${drush.bin}
      arguments:
        - cas-mock-server:user-create
        - moderator
      options:
        email: moderator@example.com
        password: moderator
        yes: null
        root: ${joinup.site_dir}
    - task: exec
      command: ${drush.bin}
      arguments:
        - cas:set-cas-username
        - moderator
        - moderator
      options:
        yes: null
        root: ${joinup.site_dir}
    - task: exec
      command: ${drush.bin}
      arguments:
        - user:create
        - user
      options:
        mail: user@example.com
        password: user
        yes: null
        root: ${joinup.site_dir}
    - task: exec
      command: ${drush.bin}
      arguments:
        - cas-mock-server:user-create
        - user
      options:
        email: user@example.com
        password: user
        yes: null
        root: ${joinup.site_dir}
    - task: exec
      command: ${drush.bin}
      arguments:
        - cas:set-cas-username
        - user
        - user
      options:
        yes: null
        root: ${joinup.site_dir}
    - task: run
      command: config-readonly:enable
