# Development configs and commands

phpstan:
  bin: ${joinup.dir}/vendor/bin/phpstan

dev:
  modules:
    - admin_toolbar
    - cas_mock_server
    - config_devel
    - config_update
    - devel
    - field_ui
    - filecache
    - joinup_cas_mock_server
    - views_ui

commands:

  # Scans the code base for deprecated code.
  dev:check-deprecated-code:
    - task: exec
      command: ${phpstan.bin} --no-progress analyse src tests/src web/modules/custom web/profiles web/themes
  dev:check-deprecated-code-contrib:
    - task: exec
      command: ${phpstan.bin} --no-progress analyse web/modules/contrib

  # Downloads all backends backups.
  dev:download-databases:
    - { task: "run", command: "mysql:download-dump" }
    - { task: "run", command: "virtuoso:download-snapshot" }
    - { task: "run", command: "solr:download-snapshot" }

  # Restores all backends from backup.
  dev:restore-databases:
    - task: run
      command: solr:restore
    - task: run
      command: virtuoso:restore
    - task: run
      command: drupal:settings
      arguments:
        - site-clone
    - task: run
      command: toolkit:install-dump

  # Rebuilds the dev environment by restoring backups and applying updates.
  dev:rebuild-environment:
    - task: run
      command: solr:restore
    - task: run
      command: virtuoso:restore
    - task: run
      command: drupal:settings
      arguments:
        - site-clone
    - task: run
      command: toolkit:install-clone

  dev:install-modules:
    - task: run
      command: drush:module-install
      arguments: ${dev.modules}

  dev:demo-users:
    # Make sure CAS mock server module is installed.
    - task: run
      command: drush:module-install
      arguments: cas_mock_server
    - task: exec
      command: ${drush.bin}
      arguments:
        - user:create
        - administrator
      options:
        mail: administrator@example.com
        password: administrator
        yes: null
        root: ${joinup.site_dir}
    - task: exec
      command: ${drush.bin}
      arguments:
        - user:role:add
        - administrator
        - administrator
      options:
        yes: null
        root: ${joinup.site_dir}
    - task: exec
      command: ${drush.bin}
      arguments:
        - cas-mock-server:user-create
        - administrator
      options:
        email: administrator@example.com
        password: administrator
        yes: null
        root: ${joinup.site_dir}
    - task: exec
      command: ${drush.bin}
      arguments:
        - cas:set-cas-username
        - administrator
        - administrator
      options:
        yes: null
        root: ${joinup.site_dir}
    - task: exec
      command: ${drush.bin}
      arguments:
        - user:create
        - moderator
      options:
        mail: moderator@example.com
        password: moderator
        yes: null
        root: ${joinup.site_dir}
    - task: exec
      command: ${drush.bin}
      arguments:
        - user:role:add
        - moderator
        - moderator
      options:
        yes: null
        root: ${joinup.site_dir}
    - task: exec
      command: ${drush.bin}
      arguments:
        - cas-mock-server:user-create
        - moderator
      options:
        email: moderator@example.com
        password: moderator
        yes: null
        root: ${joinup.site_dir}
    - task: exec
      command: ${drush.bin}
      arguments:
        - cas:set-cas-username
        - moderator
        - moderator
      options:
        yes: null
        root: ${joinup.site_dir}
    - task: exec
      command: ${drush.bin}
      arguments:
        - user:create
        - user
      options:
        mail: user@example.com
        password: user
        yes: null
        root: ${joinup.site_dir}
    - task: exec
      command: ${drush.bin}
      arguments:
        - cas-mock-server:user-create
        - user
      options:
        email: user@example.com
        password: user
        yes: null
        root: ${joinup.site_dir}
    - task: exec
      command: ${drush.bin}
      arguments:
        - cas:set-cas-username
        - user
        - user
      options:
        yes: null
        root: ${joinup.site_dir}
