# Development configs and commands

phpstan:
  bin: ${joinup.dir}/vendor/bin/phpstan

commands:
  # Scans the code base for deprecated code.
  dev:check-deprecated-code:
    - task: exec
      command: ${phpstan.bin} --no-progress analyse src tests/src web/modules/custom web/profiles web/themes
  dev:check-deprecated-code-contrib:
    - task: exec
      command: ${phpstan.bin} --no-progress analyse web/modules/contrib

  # Downloads all backends backups.
  dev:download-databases:
    - { task: "run", command: "mysql:download-dump" }
    - { task: "run", command: "virtuoso:download-snapshot" }
    - { task: "run", command: "solr:download-snapshot" }

  # Restores all backends from backup.
  dev:restore-databases:
    - task: run
      command: solr:restore
    - task: run
      command: virtuoso:restore
    - task: exec
      command: ${phing.bin}
      arguments:
        - disable-webtools-geocoding-cache
    - task: run
      command: toolkit:install-dump

  # Rebuilds the dev environment by restoring backups and applying updates.
  dev:rebuild-environment:
    - task: run
      command: dev:restore-databases
    - task: run
      command: toolkit:run-deploy
