<?php
/**
 * @file
 * Main functions and hook implementations of the Joinup user module.
 */

use \Drupal\Core\Form\FormStateInterface;
use \Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_ENTITY_TYPE_presave().
 *
 * Send a notification whenever an admin updates a user profile.
 */
function joinup_user_user_presave(AccountInterface $account) {
  // Only act on update.
  if (empty($account->id())) {
    return;
  }

  $user = \Drupal::currentUser();
  if ($user->id() == $account->id()) {
    // User changed his own profile.
    return;
  }

  /** @var \Drupal\joinup_user\ActiveFormSubmit $active_form */
  $active_form = \Drupal::getContainer()->get('joinup_user.active_form_submit');
  $active_form_id = $active_form->getFormId();
  // Only run when either submitting the user edit form, or the bulk operation
  // on admin/people.
  if (!$active_form_id || !in_array($active_form_id, ['views_form_user_admin_people_page_1', 'user_form'])) {
    return;
  }

  // Load original account object for comparison.
  $account_previous_state = \Drupal::entityManager()->getStorage('user')->loadUnchanged($account->id());
  $params['account'] = $account;
  \Drupal::service('plugin.manager.mail')->mail(
    'user',
    'email_admin_update',
    $account->getEmail(),
    $account->getPreferredLangcode(),
    $params
  );
  drupal_set_message(t('An e-mail has been send to the user to notify him on the change to his account.'));
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Settings form for the email send when an admin updates a user profile.
 */
function joinup_user_form_user_admin_settings_alter(&$form, FormStateInterface $form_state) {
  $form['#submit'][] = 'joinup_user_form_user_admin_settings_alter_submit';
  $mail_config = \Drupal::config('user.mail');
  $email_token_help = t('Available variables are: [site:name], [site:url], [user:display-name], [user:account-name], [user:mail], [site:login-url], [site:url-brief], [user:edit-url], [user:one-time-login-url], [user:cancel-url].');
  $form['email_admin_update'] = array(
    '#type' => 'details',
    '#title' => t('Account changed by administrator'),
    '#description' => t('Edit the email messages sent to member accounts edited by an administrator.'),
    '#group' => 'email',
  );
  $form['email_admin_update']['#description'] .= ' ' . $email_token_help;
  $form['email_admin_update']['user_mail_update_account_subject'] = array(
    '#type' => 'textfield',
    '#title' => t('Subject'),
    '#default_value' => $mail_config->get('email_admin_update.subject'),
    '#maxlength' => 180,
  );
  $form['email_admin_update']['user_mail_update_account_body'] = array(
    '#type' => 'textarea',
    '#title' => t('Body'),
    '#default_value' => $mail_config->get('email_admin_update.body'),
    '#rows' => 15,
  );
}

/**
 * Submit callback: Save the email settings.
 */
function joinup_user_form_user_admin_settings_alter_submit(array &$form, FormStateInterface $form_state) {
  \Drupal::configFactory()->getEditable('user.mail')
    ->set('email_admin_update.body', $form_state->getValue('user_mail_update_account_body'))
    ->set('email_admin_update.subject', $form_state->getValue('user_mail_update_account_subject'))
    ->save();
}

/**
 * Implements hook_form_alter().
 */
function joinup_user_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#validate'][] = 'joinup_user_form_alter_validate';
}

/**
 * Form validation callback: Keep track of the form being validated/submitted.
 */
function joinup_user_form_alter_validate(&$form, FormStateInterface $form_state) {
  $build_info = $form_state->getBuildInfo();
  if (isset($build_info['form_id'])) {
    /** @var \Drupal\joinup_user\ActiveFormSubmit $active_form */
    $active_form = \Drupal::getContainer()->get('joinup_user.active_form_submit');
    $active_form->setFormId($build_info['form_id']);
  }
}
