<?php

/**
 * @file
 * Main functions and hook implementations of the Joinup EU Login module.
 */

declare(strict_types = 1);

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;

/**
 * Implements hook_cron().
 */
function joinup_eulogin_cron(): void {
  $now = \Drupal::time()->getRequestTime();
  $last_updated = \Drupal::state()->get('joinup_eulogin.schema_data_updater.last_updated');
  $check_interval = \Drupal::config('joinup_eulogin.settings')->get('schema.check_interval');
  if ($now > $last_updated + $check_interval) {
    // It's time to check for a new version.
    \Drupal::service('joinup_eulogin.schema_data_updater')->update();
  }
}

/**
 * Implements hook_entity_base_field_info().
 *
 * Adds a computed field to easily retrieve the external authname of a user.
 */
function joinup_eulogin_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];

  if ($entity_type->id() === 'user') {
    $fields['eulogin_authname'] = BaseFieldDefinition::create('string')
      ->setLabel(t('EU Login name'))
      ->setDisplayConfigurable('form', FALSE)
      ->setDisplayConfigurable('display', FALSE)
      ->setComputed(TRUE)
      ->setCardinality(1)
      ->setClass('\Drupal\joinup_eulogin\JoinupEuExternalAuthnameItemList');
  }

  return $fields;
}
